/* GENERATED by the publish backend. Do not hand-edit - the next publish overwrites it. */
const MAP = {
  "community": "Aditya Athena",
  "view": {
    "w": 1000,
    "h": 1396
  },
  "levels": [
    {
      "id": "G",
      "name": "Ground",
      "underground": false
    },
    {
      "id": "P1",
      "name": "A Block B1",
      "underground": true
    },
    {
      "id": "P2",
      "name": "Basement 1 (A Block B2)",
      "underground": true
    }
  ],
  "blocks": [
    {
      "id": "A",
      "name": "Block A",
      "lobby": "lift-a",
      "floors": 15,
      "perFloor": 8,
      "ground": 8
    },
    {
      "id": "B",
      "name": "Block B",
      "lobby": "lift-b",
      "floors": 15,
      "perFloor": 5,
      "ground": 5
    },
    {
      "id": "C",
      "name": "Block C",
      "lobby": "lift-c",
      "floors": 14,
      "perFloor": 5,
      "ground": 5
    },
    {
      "id": "D",
      "name": "Block D",
      "lobby": "lift-d",
      "floors": 14,
      "perFloor": 6,
      "ground": 6
    },
    {
      "id": "E",
      "name": "Block E",
      "lobby": "lift-e",
      "floors": 14,
      "perFloor": 5,
      "ground": 5
    },
    {
      "id": "F",
      "name": "Block F",
      "lobby": "lift-f",
      "floors": 14,
      "perFloor": 5,
      "ground": 5
    }
  ],
  "slotRuns": [],
  "allotments": [],
  "areas": [
    {
      "id": "core-e",
      "level": "P2",
      "node": "lift-e",
      "name": "Block E",
      "points": [
        [
          190,
          110
        ],
        [
          350,
          110
        ],
        [
          350,
          240
        ],
        [
          190,
          240
        ]
      ]
    },
    {
      "id": "core-d",
      "level": "P2",
      "node": "lift-d",
      "name": "Block D",
      "points": [
        [
          470,
          110
        ],
        [
          640,
          110
        ],
        [
          640,
          300
        ],
        [
          470,
          300
        ]
      ]
    },
    {
      "id": "core-c",
      "level": "P2",
      "node": "lift-c",
      "name": "Block C",
      "points": [
        [
          690,
          80
        ],
        [
          840,
          80
        ],
        [
          840,
          320
        ],
        [
          690,
          320
        ]
      ]
    },
    {
      "id": "core-f",
      "level": "P2",
      "node": "lift-f",
      "name": "Block F",
      "points": [
        [
          120,
          355
        ],
        [
          340,
          355
        ],
        [
          340,
          530
        ],
        [
          120,
          530
        ]
      ]
    },
    {
      "id": "core-b",
      "level": "P2",
      "node": "lift-b",
      "name": "Block B",
      "points": [
        [
          700,
          370
        ],
        [
          840,
          370
        ],
        [
          840,
          650
        ],
        [
          700,
          650
        ]
      ]
    },
    {
      "id": "core-a",
      "level": "P2",
      "node": "lift-a",
      "name": "Block A",
      "points": [
        [
          550,
          690
        ],
        [
          690,
          690
        ],
        [
          690,
          920
        ],
        [
          550,
          920
        ]
      ]
    },
    {
      "id": "core-a2",
      "level": "P2",
      "node": "lift-a2",
      "name": "Block A (east)",
      "points": [
        [
          710,
          690
        ],
        [
          850,
          690
        ],
        [
          850,
          940
        ],
        [
          710,
          940
        ]
      ]
    },
    {
      "id": "visitor-area",
      "level": "P2",
      "node": "visitor",
      "name": "Visitor Parking",
      "points": [
        [
          665,
          1200
        ],
        [
          815,
          1200
        ],
        [
          815,
          1345
        ],
        [
          665,
          1345
        ]
      ]
    }
  ],
  "nodes": [
    {
      "id": "gate",
      "level": "G",
      "xy": [
        100,
        560
      ],
      "name": "Main Gate",
      "cat": "entry",
      "dest": true,
      "anchor": true
    },
    {
      "id": "lift-e",
      "level": "P2",
      "xy": [
        245,
        160
      ],
      "name": "Block E Lift",
      "cat": "block",
      "dest": true,
      "anchor": true,
      "lift": true
    },
    {
      "id": "lift-d",
      "level": "P2",
      "xy": [
        580,
        210
      ],
      "name": "Block D Lift",
      "cat": "block",
      "dest": true,
      "anchor": true,
      "lift": true
    },
    {
      "id": "lift-c",
      "level": "P2",
      "xy": [
        775,
        195
      ],
      "name": "Block C Lift",
      "cat": "block",
      "dest": true,
      "anchor": true,
      "lift": true
    },
    {
      "id": "lift-f",
      "level": "P2",
      "xy": [
        225,
        385
      ],
      "name": "Block F Lift",
      "cat": "block",
      "dest": true,
      "anchor": true,
      "lift": true
    },
    {
      "id": "lift-b",
      "level": "P2",
      "xy": [
        775,
        505
      ],
      "name": "Block B Lift",
      "cat": "block",
      "dest": true,
      "anchor": true,
      "lift": true
    },
    {
      "id": "lift-a",
      "level": "P2",
      "xy": [
        668,
        790
      ],
      "name": "Block A Lift",
      "cat": "block",
      "dest": true,
      "anchor": true,
      "lift": true
    },
    {
      "id": "lift-a2",
      "level": "P2",
      "xy": [
        790,
        800
      ],
      "name": "Block A Lift (east)",
      "cat": "block",
      "dest": true,
      "anchor": true,
      "lift": true
    },
    {
      "id": "visitor",
      "level": "P2",
      "xy": [
        700,
        1262
      ],
      "name": "Visitor Parking",
      "cat": "parking",
      "dest": true,
      "anchor": true
    },
    {
      "id": "g-forecourt",
      "level": "G",
      "xy": [
        100,
        440
      ],
      "name": "Block A forecourt"
    },
    {
      "id": "g-apron",
      "level": "G",
      "xy": [
        100,
        320
      ],
      "name": "Concrete apron by Block A"
    },
    {
      "id": "g-bend",
      "level": "G",
      "xy": [
        330,
        320
      ],
      "name": "Road along the boundary wall"
    },
    {
      "id": "g-guard",
      "level": "G",
      "xy": [
        520,
        400
      ],
      "name": "Guard post"
    },
    {
      "id": "g-main-ramp",
      "level": "G",
      "xy": [
        470,
        470
      ],
      "name": "Basement entry ramp"
    },
    {
      "id": "g-a-ramp",
      "level": "G",
      "xy": [
        -60,
        300
      ],
      "name": "Block A ramp (pergola)"
    },
    {
      "id": "main-ramp-foot",
      "level": "P2",
      "xy": [
        640,
        636
      ],
      "name": "Foot of the entry ramp",
      "cat": "entry",
      "anchor": true
    },
    {
      "id": "a-ramp-foot",
      "level": "P1",
      "xy": [
        398,
        301
      ],
      "name": "Foot of the Block A ramp",
      "cat": "entry"
    },
    {
      "id": "a2-ramp-top",
      "level": "P1",
      "xy": [
        590,
        301
      ],
      "name": "Top of the ramp down to Basement 1"
    },
    {
      "id": "a2-ramp-foot",
      "level": "P2",
      "xy": [
        623,
        1178
      ],
      "name": "Foot of the ramp from Block A"
    },
    {
      "id": "p2-1",
      "level": "P2",
      "xy": [
        160,
        175
      ]
    },
    {
      "id": "p2-2",
      "level": "P2",
      "xy": [
        160,
        104
      ]
    },
    {
      "id": "p2-3",
      "level": "P2",
      "xy": [
        175,
        95
      ]
    },
    {
      "id": "p2-4",
      "level": "P2",
      "xy": [
        449,
        95
      ]
    },
    {
      "id": "p2-5",
      "level": "P2",
      "xy": [
        656,
        90
      ]
    },
    {
      "id": "p2-6",
      "level": "P2",
      "xy": [
        656,
        66
      ]
    },
    {
      "id": "p2-7",
      "level": "P2",
      "xy": [
        836,
        66
      ]
    },
    {
      "id": "p2-8",
      "level": "P2",
      "xy": [
        656,
        220
      ]
    },
    {
      "id": "p2-9",
      "level": "P2",
      "xy": [
        676,
        262
      ]
    },
    {
      "id": "p2-10",
      "level": "P2",
      "xy": [
        679,
        337
      ]
    },
    {
      "id": "p2-11",
      "level": "P2",
      "xy": [
        846,
        340
      ]
    },
    {
      "id": "p2-12",
      "level": "P2",
      "xy": [
        438,
        264
      ]
    },
    {
      "id": "p2-13",
      "level": "P2",
      "xy": [
        452,
        335
      ]
    },
    {
      "id": "p2-14",
      "level": "P2",
      "xy": [
        158,
        262
      ]
    },
    {
      "id": "p2-15",
      "level": "P2",
      "xy": [
        107,
        341
      ]
    },
    {
      "id": "p2-16",
      "level": "P2",
      "xy": [
        367,
        336
      ]
    },
    {
      "id": "p2-17",
      "level": "P2",
      "xy": [
        851,
        682
      ]
    },
    {
      "id": "p2-18",
      "level": "P2",
      "xy": [
        856,
        957
      ]
    },
    {
      "id": "p2-19",
      "level": "P2",
      "xy": [
        368,
        528
      ]
    },
    {
      "id": "p2-20",
      "level": "P2",
      "xy": [
        387,
        540
      ]
    },
    {
      "id": "p2-21",
      "level": "P2",
      "xy": [
        81,
        358
      ]
    },
    {
      "id": "p2-22",
      "level": "P2",
      "xy": [
        83,
        515
      ]
    },
    {
      "id": "p2-23",
      "level": "P2",
      "xy": [
        105,
        532
      ]
    },
    {
      "id": "p2-24",
      "level": "P2",
      "xy": [
        464,
        540
      ]
    },
    {
      "id": "p2-25",
      "level": "P2",
      "xy": [
        680,
        536
      ]
    },
    {
      "id": "p2-26",
      "level": "P2",
      "xy": [
        464,
        422
      ]
    },
    {
      "id": "p2-27",
      "level": "P2",
      "xy": [
        474,
        667
      ]
    },
    {
      "id": "p2-28",
      "level": "P2",
      "xy": [
        679,
        418
      ]
    },
    {
      "id": "p2-29",
      "level": "P2",
      "xy": [
        698,
        689
      ]
    },
    {
      "id": "p2-30",
      "level": "P2",
      "xy": [
        709,
        968
      ]
    },
    {
      "id": "p2-31",
      "level": "P2",
      "xy": [
        538,
        677
      ]
    },
    {
      "id": "p2-32",
      "level": "P2",
      "xy": [
        622,
        669
      ]
    },
    {
      "id": "p2-33",
      "level": "P2",
      "xy": [
        546,
        855
      ]
    },
    {
      "id": "p2-34",
      "level": "P2",
      "xy": [
        600,
        919
      ]
    },
    {
      "id": "p2-35",
      "level": "P2",
      "xy": [
        620,
        964
      ]
    },
    {
      "id": "p2-36",
      "level": "P2",
      "xy": [
        680,
        971
      ]
    },
    {
      "id": "p2-37",
      "level": "P2",
      "xy": [
        765,
        971
      ]
    },
    {
      "id": "p2-38",
      "level": "P2",
      "xy": [
        891,
        965
      ]
    },
    {
      "id": "p2-39",
      "level": "P2",
      "xy": [
        680,
        1200
      ]
    },
    {
      "id": "p2-40",
      "level": "P2",
      "xy": [
        680,
        1335
      ]
    },
    {
      "id": "p2-41",
      "level": "P2",
      "xy": [
        765,
        1200
      ]
    },
    {
      "id": "p2-42",
      "level": "P2",
      "xy": [
        770,
        1290
      ]
    },
    {
      "id": "p2-43",
      "level": "P2",
      "xy": [
        797,
        1300
      ]
    },
    {
      "id": "p2-44",
      "level": "P2",
      "xy": [
        799,
        1334
      ]
    },
    {
      "id": "p1-1",
      "level": "P1",
      "xy": [
        215,
        348
      ]
    },
    {
      "id": "p1-2",
      "level": "P1",
      "xy": [
        632,
        358
      ]
    },
    {
      "id": "p1-3",
      "level": "P1",
      "xy": [
        213,
        440
      ]
    },
    {
      "id": "p1-4",
      "level": "P1",
      "xy": [
        318,
        452
      ]
    },
    {
      "id": "p1-5",
      "level": "P1",
      "xy": [
        610,
        455
      ]
    },
    {
      "id": "p1-6",
      "level": "P1",
      "xy": [
        640,
        440
      ]
    },
    {
      "id": "p1-7",
      "level": "P1",
      "xy": [
        765,
        225
      ]
    },
    {
      "id": "p1-8",
      "level": "P1",
      "xy": [
        638,
        300
      ]
    },
    {
      "id": "p1-9",
      "level": "P1",
      "xy": [
        642,
        390
      ]
    },
    {
      "id": "p1-10",
      "level": "P1",
      "xy": [
        640,
        555
      ]
    },
    {
      "id": "p1-11",
      "level": "P1",
      "xy": [
        640,
        680
      ]
    },
    {
      "id": "p1-12",
      "level": "P1",
      "xy": [
        937,
        382
      ]
    },
    {
      "id": "p1-13",
      "level": "P1",
      "xy": [
        943,
        340
      ]
    },
    {
      "id": "p1-14",
      "level": "P1",
      "xy": [
        942,
        545
      ]
    },
    {
      "id": "p1-15",
      "level": "P1",
      "xy": [
        905,
        560
      ]
    },
    {
      "id": "p1-16",
      "level": "P1",
      "xy": [
        822,
        205
      ]
    },
    {
      "id": "p1-17",
      "level": "P1",
      "xy": [
        943,
        190
      ]
    },
    {
      "id": "p1-18",
      "level": "P1",
      "xy": [
        700,
        668
      ]
    },
    {
      "id": "p1-19",
      "level": "P1",
      "xy": [
        915,
        665
      ]
    },
    {
      "id": "p2-46",
      "level": "P2",
      "xy": [
        245,
        95
      ]
    },
    {
      "id": "p2-48",
      "level": "P2",
      "xy": [
        656,
        210
      ]
    },
    {
      "id": "p2-50",
      "level": "P2",
      "xy": [
        840.6,
        192.6
      ]
    },
    {
      "id": "p2-52",
      "level": "P2",
      "xy": [
        224.1,
        338.7
      ]
    },
    {
      "id": "p2-54",
      "level": "P2",
      "xy": [
        848.4,
        503.9
      ]
    },
    {
      "id": "p2-56",
      "level": "P2",
      "xy": [
        701.9,
        788.7
      ]
    },
    {
      "id": "p2-58",
      "level": "P2",
      "xy": [
        853.1,
        798.9
      ]
    },
    {
      "id": "p2-60",
      "level": "P2",
      "xy": [
        680,
        1262
      ]
    },
    {
      "id": "p2-62",
      "level": "P2",
      "xy": [
        630.7,
        671.3
      ]
    },
    {
      "id": "p1-21",
      "level": "P1",
      "xy": [
        396.8,
        352.4
      ]
    },
    {
      "id": "p2-64",
      "level": "P2",
      "xy": [
        680,
        1178
      ]
    }
  ],
  "edges": [
    {
      "id": "e-1",
      "from": "p2-1",
      "to": "p2-2",
      "mode": [
        "car",
        "foot"
      ],
      "len": 13.5,
      "instruction": null
    },
    {
      "id": "e-2",
      "from": "p2-2",
      "to": "p2-3",
      "mode": [
        "car",
        "foot"
      ],
      "len": 3.3,
      "instruction": null
    },
    {
      "id": "e-4",
      "from": "p2-4",
      "to": "p2-5",
      "mode": [
        "car",
        "foot"
      ],
      "len": 39.3,
      "instruction": null
    },
    {
      "id": "e-5",
      "from": "p2-6",
      "to": "p2-7",
      "mode": [
        "car",
        "foot"
      ],
      "len": 34.2,
      "instruction": null
    },
    {
      "id": "e-6",
      "from": "p2-6",
      "to": "p2-5",
      "mode": [
        "car",
        "foot"
      ],
      "len": 4.6,
      "instruction": null
    },
    {
      "id": "e-8",
      "from": "p2-8",
      "to": "p2-9",
      "mode": [
        "car",
        "foot"
      ],
      "len": 8.8,
      "instruction": null
    },
    {
      "id": "e-9",
      "from": "p2-9",
      "to": "p2-10",
      "mode": [
        "car",
        "foot"
      ],
      "len": 14.3,
      "instruction": null
    },
    {
      "id": "e-11",
      "from": "p2-4",
      "to": "p2-12",
      "mode": [
        "car",
        "foot"
      ],
      "len": 32.2,
      "instruction": null
    },
    {
      "id": "e-12",
      "from": "p2-12",
      "to": "p2-13",
      "mode": [
        "car",
        "foot"
      ],
      "len": 13.7,
      "instruction": null
    },
    {
      "id": "e-13",
      "from": "p2-1",
      "to": "p2-14",
      "mode": [
        "car",
        "foot"
      ],
      "len": 16.5,
      "instruction": null
    },
    {
      "id": "e-14",
      "from": "p2-14",
      "to": "p2-15",
      "mode": [
        "car",
        "foot"
      ],
      "len": 17.9,
      "instruction": null
    },
    {
      "id": "e-15",
      "from": "p2-14",
      "to": "p2-12",
      "mode": [
        "car",
        "foot"
      ],
      "len": 53.2,
      "instruction": null
    },
    {
      "id": "e-17",
      "from": "p2-16",
      "to": "p2-13",
      "mode": [
        "car",
        "foot"
      ],
      "len": 16.2,
      "instruction": null
    },
    {
      "id": "e-18",
      "from": "p2-13",
      "to": "p2-10",
      "mode": [
        "car",
        "foot"
      ],
      "len": 43.1,
      "instruction": null
    },
    {
      "id": "e-19",
      "from": "p2-10",
      "to": "p2-11",
      "mode": [
        "car",
        "foot"
      ],
      "len": 31.7,
      "instruction": null
    },
    {
      "id": "e-22",
      "from": "p2-16",
      "to": "p2-19",
      "mode": [
        "car",
        "foot"
      ],
      "len": 36.5,
      "instruction": null
    },
    {
      "id": "e-23",
      "from": "p2-19",
      "to": "p2-20",
      "mode": [
        "car",
        "foot"
      ],
      "len": 4.3,
      "instruction": null
    },
    {
      "id": "e-24",
      "from": "p2-15",
      "to": "p2-21",
      "mode": [
        "car",
        "foot"
      ],
      "len": 5.9,
      "instruction": null
    },
    {
      "id": "e-25",
      "from": "p2-21",
      "to": "p2-22",
      "mode": [
        "car",
        "foot"
      ],
      "len": 29.8,
      "instruction": null
    },
    {
      "id": "e-26",
      "from": "p2-22",
      "to": "p2-23",
      "mode": [
        "car",
        "foot"
      ],
      "len": 5.3,
      "instruction": null
    },
    {
      "id": "e-27",
      "from": "p2-23",
      "to": "p2-20",
      "mode": [
        "car",
        "foot"
      ],
      "len": 53.6,
      "instruction": null
    },
    {
      "id": "e-28",
      "from": "p2-20",
      "to": "p2-24",
      "mode": [
        "car",
        "foot"
      ],
      "len": 14.6,
      "instruction": null
    },
    {
      "id": "e-29",
      "from": "p2-24",
      "to": "p2-25",
      "mode": [
        "car",
        "foot"
      ],
      "len": 41,
      "instruction": null
    },
    {
      "id": "e-30",
      "from": "p2-13",
      "to": "p2-26",
      "mode": [
        "car",
        "foot"
      ],
      "len": 16.7,
      "instruction": null
    },
    {
      "id": "e-31",
      "from": "p2-26",
      "to": "p2-24",
      "mode": [
        "car",
        "foot"
      ],
      "len": 22.4,
      "instruction": null
    },
    {
      "id": "e-32",
      "from": "p2-24",
      "to": "p2-27",
      "mode": [
        "car",
        "foot"
      ],
      "len": 24.2,
      "instruction": null
    },
    {
      "id": "e-33",
      "from": "p2-26",
      "to": "p2-28",
      "mode": [
        "car",
        "foot"
      ],
      "len": 40.9,
      "instruction": null
    },
    {
      "id": "e-34",
      "from": "p2-10",
      "to": "p2-28",
      "mode": [
        "car",
        "foot"
      ],
      "len": 15.4,
      "instruction": null
    },
    {
      "id": "e-35",
      "from": "p2-28",
      "to": "p2-25",
      "mode": [
        "car",
        "foot"
      ],
      "len": 22.4,
      "instruction": null
    },
    {
      "id": "e-36",
      "from": "p2-25",
      "to": "p2-29",
      "mode": [
        "car",
        "foot"
      ],
      "len": 29.3,
      "instruction": null
    },
    {
      "id": "e-38",
      "from": "p2-27",
      "to": "p2-31",
      "mode": [
        "car",
        "foot"
      ],
      "len": 12.3,
      "instruction": null
    },
    {
      "id": "e-39",
      "from": "p2-31",
      "to": "p2-32",
      "mode": [
        "car",
        "foot"
      ],
      "len": 16,
      "instruction": null
    },
    {
      "id": "e-41",
      "from": "p2-29",
      "to": "p2-17",
      "mode": [
        "car",
        "foot"
      ],
      "len": 29.1,
      "instruction": null
    },
    {
      "id": "e-42",
      "from": "p2-31",
      "to": "p2-33",
      "mode": [
        "car",
        "foot"
      ],
      "len": 33.9,
      "instruction": null
    },
    {
      "id": "e-43",
      "from": "p2-33",
      "to": "p2-34",
      "mode": [
        "car",
        "foot"
      ],
      "len": 15.9,
      "instruction": null
    },
    {
      "id": "e-44",
      "from": "p2-34",
      "to": "p2-35",
      "mode": [
        "car",
        "foot"
      ],
      "len": 9.4,
      "instruction": null
    },
    {
      "id": "e-45",
      "from": "p2-35",
      "to": "p2-36",
      "mode": [
        "car",
        "foot"
      ],
      "len": 11.5,
      "instruction": null
    },
    {
      "id": "e-46",
      "from": "p2-36",
      "to": "p2-30",
      "mode": [
        "car",
        "foot"
      ],
      "len": 5.5,
      "instruction": null
    },
    {
      "id": "e-47",
      "from": "p2-30",
      "to": "p2-37",
      "mode": [
        "car",
        "foot"
      ],
      "len": 10.7,
      "instruction": null
    },
    {
      "id": "e-48",
      "from": "p2-37",
      "to": "p2-18",
      "mode": [
        "car",
        "foot"
      ],
      "len": 17.5,
      "instruction": null
    },
    {
      "id": "e-49",
      "from": "p2-18",
      "to": "p2-38",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6.8,
      "instruction": null
    },
    {
      "id": "e-52",
      "from": "p2-37",
      "to": "p2-41",
      "mode": [
        "car",
        "foot"
      ],
      "len": 43.5,
      "instruction": null
    },
    {
      "id": "e-53",
      "from": "p2-41",
      "to": "p2-42",
      "mode": [
        "car",
        "foot"
      ],
      "len": 17.1,
      "instruction": null
    },
    {
      "id": "e-54",
      "from": "p2-42",
      "to": "p2-43",
      "mode": [
        "car",
        "foot"
      ],
      "len": 5.5,
      "instruction": null
    },
    {
      "id": "e-55",
      "from": "p2-43",
      "to": "p2-44",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6.5,
      "instruction": null
    },
    {
      "id": "e-56",
      "from": "p2-39",
      "to": "p2-41",
      "mode": [
        "car",
        "foot"
      ],
      "len": 16.1,
      "instruction": null
    },
    {
      "id": "e-57",
      "from": "p2-40",
      "to": "p2-44",
      "mode": [
        "car",
        "foot"
      ],
      "len": 22.6,
      "instruction": null
    },
    {
      "id": "e-59",
      "from": "p1-1",
      "to": "p1-3",
      "mode": [
        "car",
        "foot"
      ],
      "len": 14.6,
      "instruction": null
    },
    {
      "id": "e-60",
      "from": "p1-3",
      "to": "p1-4",
      "mode": [
        "car",
        "foot"
      ],
      "len": 16.8,
      "instruction": null
    },
    {
      "id": "e-61",
      "from": "p1-4",
      "to": "p1-5",
      "mode": [
        "car",
        "foot"
      ],
      "len": 46.4,
      "instruction": null
    },
    {
      "id": "e-62",
      "from": "p1-5",
      "to": "p1-6",
      "mode": [
        "car",
        "foot"
      ],
      "len": 5.3,
      "instruction": null
    },
    {
      "id": "e-63",
      "from": "p1-7",
      "to": "p1-8",
      "mode": [
        "car",
        "foot"
      ],
      "len": 23.5,
      "instruction": null
    },
    {
      "id": "e-64",
      "from": "p1-8",
      "to": "p1-2",
      "mode": [
        "car",
        "foot"
      ],
      "len": 9.3,
      "instruction": null
    },
    {
      "id": "e-65",
      "from": "p1-2",
      "to": "p1-9",
      "mode": [
        "car",
        "foot"
      ],
      "len": 5.3,
      "instruction": null
    },
    {
      "id": "e-66",
      "from": "p1-9",
      "to": "p1-6",
      "mode": [
        "car",
        "foot"
      ],
      "len": 8,
      "instruction": null
    },
    {
      "id": "e-67",
      "from": "p1-6",
      "to": "p1-10",
      "mode": [
        "car",
        "foot"
      ],
      "len": 18.3,
      "instruction": null
    },
    {
      "id": "e-68",
      "from": "p1-10",
      "to": "p1-11",
      "mode": [
        "car",
        "foot"
      ],
      "len": 19.9,
      "instruction": null
    },
    {
      "id": "e-69",
      "from": "p1-9",
      "to": "p1-12",
      "mode": [
        "car",
        "foot"
      ],
      "len": 46.9,
      "instruction": null
    },
    {
      "id": "e-70",
      "from": "p1-12",
      "to": "p1-13",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6.7,
      "instruction": null
    },
    {
      "id": "e-71",
      "from": "p1-12",
      "to": "p1-14",
      "mode": [
        "car",
        "foot"
      ],
      "len": 25.9,
      "instruction": null
    },
    {
      "id": "e-72",
      "from": "p1-14",
      "to": "p1-15",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6.3,
      "instruction": null
    },
    {
      "id": "e-73",
      "from": "p1-15",
      "to": "p1-10",
      "mode": [
        "car",
        "foot"
      ],
      "len": 42.1,
      "instruction": null
    },
    {
      "id": "e-74",
      "from": "p1-7",
      "to": "p1-16",
      "mode": [
        "car",
        "foot"
      ],
      "len": 9.6,
      "instruction": null
    },
    {
      "id": "e-75",
      "from": "p1-16",
      "to": "p1-17",
      "mode": [
        "car",
        "foot"
      ],
      "len": 19.4,
      "instruction": null
    },
    {
      "id": "e-76",
      "from": "p1-11",
      "to": "p1-18",
      "mode": [
        "car",
        "foot"
      ],
      "len": 9.7,
      "instruction": null
    },
    {
      "id": "e-77",
      "from": "p1-18",
      "to": "p1-19",
      "mode": [
        "car",
        "foot"
      ],
      "len": 34.2,
      "instruction": null
    },
    {
      "id": "e-78",
      "from": "p2-3",
      "to": "p2-46",
      "mode": [
        "car",
        "foot"
      ],
      "len": 13.3,
      "instruction": null
    },
    {
      "id": "e-79",
      "from": "p2-46",
      "to": "p2-4",
      "mode": [
        "car",
        "foot"
      ],
      "len": 38.8,
      "instruction": null
    },
    {
      "id": "e-80",
      "from": "p2-46",
      "to": "lift-e",
      "mode": [
        "car",
        "foot"
      ],
      "len": 12.3,
      "instruction": "Block E lift and stairs are off the aisle here.",
      "instructionRev": "Come out of the Block E lift lobby into the aisle."
    },
    {
      "id": "e-81",
      "from": "p2-5",
      "to": "p2-48",
      "mode": [
        "car",
        "foot"
      ],
      "len": 22.8,
      "instruction": null
    },
    {
      "id": "e-82",
      "from": "p2-48",
      "to": "p2-8",
      "mode": [
        "car",
        "foot"
      ],
      "len": 1.9,
      "instruction": null
    },
    {
      "id": "e-83",
      "from": "p2-48",
      "to": "lift-d",
      "mode": [
        "car",
        "foot"
      ],
      "len": 14.4,
      "instruction": "Block D lift and stairs are off the aisle here.",
      "instructionRev": "Come out of the Block D lift lobby into the aisle."
    },
    {
      "id": "e-84",
      "from": "p2-7",
      "to": "p2-50",
      "mode": [
        "car",
        "foot"
      ],
      "len": 24.1,
      "instruction": null
    },
    {
      "id": "e-85",
      "from": "p2-50",
      "to": "p2-11",
      "mode": [
        "car",
        "foot"
      ],
      "len": 28,
      "instruction": null
    },
    {
      "id": "e-86",
      "from": "p2-50",
      "to": "lift-c",
      "mode": [
        "car",
        "foot"
      ],
      "len": 12.5,
      "instruction": "Block C lift and stairs are off the aisle here.",
      "instructionRev": "Come out of the Block C lift lobby into the aisle."
    },
    {
      "id": "e-87",
      "from": "p2-15",
      "to": "p2-52",
      "mode": [
        "car",
        "foot"
      ],
      "len": 22.3,
      "instruction": null
    },
    {
      "id": "e-88",
      "from": "p2-52",
      "to": "p2-16",
      "mode": [
        "car",
        "foot"
      ],
      "len": 27.2,
      "instruction": null
    },
    {
      "id": "e-89",
      "from": "p2-52",
      "to": "lift-f",
      "mode": [
        "car",
        "foot"
      ],
      "len": 8.8,
      "instruction": "Block F lift and stairs are off the aisle here.",
      "instructionRev": "Come out of the Block F lift lobby into the aisle."
    },
    {
      "id": "e-90",
      "from": "p2-11",
      "to": "p2-54",
      "mode": [
        "car",
        "foot"
      ],
      "len": 31.1,
      "instruction": null
    },
    {
      "id": "e-91",
      "from": "p2-54",
      "to": "p2-17",
      "mode": [
        "car",
        "foot"
      ],
      "len": 33.8,
      "instruction": null
    },
    {
      "id": "e-92",
      "from": "p2-54",
      "to": "lift-b",
      "mode": [
        "car",
        "foot"
      ],
      "len": 13.9,
      "instruction": "Block B lift and stairs are off the aisle here.",
      "instructionRev": "Come out of the Block B lift lobby into the aisle."
    },
    {
      "id": "e-93",
      "from": "p2-29",
      "to": "p2-56",
      "mode": [
        "car",
        "foot"
      ],
      "len": 19,
      "instruction": null
    },
    {
      "id": "e-94",
      "from": "p2-56",
      "to": "p2-30",
      "mode": [
        "car",
        "foot"
      ],
      "len": 34.1,
      "instruction": null
    },
    {
      "id": "e-95",
      "from": "p2-56",
      "to": "lift-a",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6.4,
      "instruction": "Block A lift and stairs are off the aisle here.",
      "instructionRev": "Come out of the Block A lift lobby into the aisle."
    },
    {
      "id": "e-96",
      "from": "p2-17",
      "to": "p2-58",
      "mode": [
        "car",
        "foot"
      ],
      "len": 22.2,
      "instruction": null
    },
    {
      "id": "e-97",
      "from": "p2-58",
      "to": "p2-18",
      "mode": [
        "car",
        "foot"
      ],
      "len": 30,
      "instruction": null
    },
    {
      "id": "e-98",
      "from": "p2-58",
      "to": "lift-a2",
      "mode": [
        "car",
        "foot"
      ],
      "len": 12,
      "instruction": "The second Block A lift and stairs are off the aisle here.",
      "instructionRev": "Come out of the Block A lift lobby into the aisle."
    },
    {
      "id": "e-99",
      "from": "p2-39",
      "to": "p2-60",
      "mode": [
        "car",
        "foot"
      ],
      "len": 11.8,
      "instruction": null
    },
    {
      "id": "e-100",
      "from": "p2-60",
      "to": "p2-40",
      "mode": [
        "car",
        "foot"
      ],
      "len": 13.9,
      "instruction": null
    },
    {
      "id": "e-101",
      "from": "p2-60",
      "to": "visitor",
      "mode": [
        "car",
        "foot"
      ],
      "len": 3.8,
      "instruction": "Visitor parking: the bays marked VP along this aisle.",
      "instructionRev": "Come out of the visitor bays into the aisle."
    },
    {
      "id": "e-102",
      "from": "p2-32",
      "to": "p2-62",
      "mode": [
        "car",
        "foot"
      ],
      "len": 1.7,
      "instruction": null
    },
    {
      "id": "e-103",
      "from": "p2-29",
      "to": "p2-62",
      "mode": [
        "car",
        "foot"
      ],
      "len": 13.2,
      "instruction": null,
      "oneway": true
    },
    {
      "id": "e-104",
      "from": "p2-62",
      "to": "main-ramp-foot",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6,
      "instruction": "Turn towards the foot of the entry ramp.",
      "instructionRev": "At the foot of the ramp, cross the speed breaker and turn left under the sign '← B, C, D, E, F, A'.",
      "photo": "main-ramp-foot-left-b1"
    },
    {
      "id": "e-105",
      "from": "p1-1",
      "to": "p1-21",
      "mode": [
        "car",
        "foot"
      ],
      "len": 28.9,
      "instruction": null
    },
    {
      "id": "e-106",
      "from": "p1-21",
      "to": "p1-2",
      "mode": [
        "car",
        "foot"
      ],
      "len": 37.4,
      "instruction": null
    },
    {
      "id": "e-107",
      "from": "p1-21",
      "to": "a-ramp-foot",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6,
      "instruction": "Turn towards the foot of the Block A ramp.",
      "instructionRev": "At the foot of the ramp, cross the steel grating and turn sharp left round the end of the wall.",
      "photo": "ablock-b1-ramp-foot-left"
    },
    {
      "id": "e-108",
      "from": "p1-8",
      "to": "a2-ramp-top",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6,
      "instruction": "In the open area by the end wall, sweep sharp left onto the down ramp.",
      "instructionRev": "Come off the ramp into Block A's B1."
    },
    {
      "id": "e-109",
      "from": "p2-36",
      "to": "p2-64",
      "mode": [
        "car",
        "foot"
      ],
      "len": 39.3,
      "instruction": null
    },
    {
      "id": "e-110",
      "from": "p2-64",
      "to": "p2-39",
      "mode": [
        "car",
        "foot"
      ],
      "len": 4.2,
      "instruction": null
    },
    {
      "id": "e-111",
      "from": "p2-64",
      "to": "a2-ramp-foot",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6,
      "instruction": "Turn towards the ramp up to Block A's B1.",
      "instructionRev": "At the foot of the ramp, with a blank wall ahead, turn left round the end of the ramp wall into the hall.",
      "photo": "ablock-b2-ramp-foot-left"
    },
    {
      "id": "e-112",
      "from": "gate",
      "to": "g-forecourt",
      "mode": [
        "car",
        "foot"
      ],
      "len": 30,
      "instruction": "Come in through the main gate and follow the paver driveway towards Block A.",
      "instructionRev": "Follow the paver driveway back to the main gate."
    },
    {
      "id": "e-113",
      "from": "g-forecourt",
      "to": "g-apron",
      "mode": [
        "car",
        "foot"
      ],
      "len": 25,
      "instruction": "At Block A's forecourt keep left round the planter, then drive along the front of Block A with the hedge on your left until the pavers end.",
      "instructionRev": "Drive back along the front of Block A to the forecourt.",
      "photo": "ablock-block-a-forecourt-left"
    },
    {
      "id": "e-114",
      "from": "g-apron",
      "to": "g-bend",
      "mode": [
        "car",
        "foot"
      ],
      "len": 25,
      "instruction": "On the concrete apron, turn right at the clubhouse garden wall and go over the speed breaker.",
      "instructionRev": "Follow the road back to the concrete apron by Block A.",
      "photo": "main-apron-right-turn"
    },
    {
      "id": "e-115",
      "from": "g-bend",
      "to": "g-guard",
      "mode": [
        "car",
        "foot"
      ],
      "len": 45,
      "instruction": "Follow the road round the long right-hand bend, over the second speed breaker, to the guard at the red barricades.",
      "instructionRev": "Follow the road back round the bend towards Block A."
    },
    {
      "id": "e-116",
      "from": "g-guard",
      "to": "g-main-ramp",
      "mode": [
        "car",
        "foot"
      ],
      "len": 10,
      "instruction": "At the guard, turn right under the 7.2 ft clearance bar: BASEMENT ENTRY FOR A, B, C, D, E, F.",
      "instructionRev": "Come off the ramp and turn left past the guard.",
      "photo": "main-guard-right-under-bar"
    },
    {
      "id": "e-117",
      "from": "g-apron",
      "to": "g-a-ramp",
      "mode": [
        "car",
        "foot"
      ],
      "len": 15,
      "instruction": "On the concrete apron, turn sharp left towards the CLUBHOUSE ENTRANCE / GUEST PARKING sign and the steel pergola.",
      "instructionRev": "Come off the Block A ramp onto the concrete apron.",
      "photo": "ablock-apron-guest-parking-left"
    },
    {
      "id": "e-118",
      "from": "g-main-ramp",
      "to": "main-ramp-foot",
      "mode": [
        "car",
        "foot"
      ],
      "len": 22,
      "instruction": "Drive straight down the covered ramp into Basement 1.",
      "instructionRev": "Drive up the entry ramp to the ground."
    },
    {
      "id": "e-119",
      "from": "g-a-ramp",
      "to": "a-ramp-foot",
      "mode": [
        "car",
        "foot"
      ],
      "len": 20,
      "instruction": "Drive straight down the covered ramp under the pergola into Block A's B1 (7.2 ft clearance).",
      "instructionRev": "Drive up the Block A ramp to the ground."
    },
    {
      "id": "e-120",
      "from": "a2-ramp-top",
      "to": "a2-ramp-foot",
      "mode": [
        "car",
        "foot"
      ],
      "len": 22,
      "instruction": "Drive straight down the ramp to Basement 1 (A Block B2).",
      "instructionRev": "Drive up the ramp to Block A's B1."
    }
  ],
  "slots": [
    {
      "id": "s-1",
      "edge": "e-109",
      "t": 0.637,
      "side": 1,
      "flat": "A-503"
    },
    {
      "id": "s-2",
      "edge": "e-97",
      "t": 0.723,
      "side": 1,
      "flat": "A-604"
    },
    {
      "id": "s-3",
      "edge": "e-96",
      "t": 0.824,
      "side": -1,
      "flat": "A-502"
    },
    {
      "id": "s-4",
      "edge": "e-48",
      "t": 0.982,
      "side": -1,
      "flat": "A-1104"
    },
    {
      "id": "s-5",
      "edge": "e-52",
      "t": 0.462,
      "side": -1,
      "flat": "A-1102"
    },
    {
      "id": "s-6",
      "edge": "e-97",
      "t": 0.161,
      "side": -1,
      "flat": "A-1103"
    },
    {
      "id": "s-7",
      "edge": "e-48",
      "t": 0.658,
      "side": -1,
      "flat": "A-1402"
    },
    {
      "id": "s-8",
      "edge": "e-52",
      "t": 0.268,
      "side": -1,
      "flat": "A-401"
    },
    {
      "id": "s-9",
      "edge": "e-96",
      "t": 0.496,
      "side": -1,
      "flat": "B-202"
    },
    {
      "id": "s-10",
      "edge": "e-97",
      "t": 0.325,
      "side": 1,
      "flat": "A-506"
    },
    {
      "id": "s-11",
      "edge": "e-96",
      "t": 0.339,
      "side": -1,
      "flat": "B-1201"
    },
    {
      "id": "s-12",
      "edge": "e-97",
      "t": 0.518,
      "side": 1,
      "flat": "A-1402"
    },
    {
      "id": "s-13",
      "edge": "e-47",
      "t": 0.109,
      "side": 1,
      "flat": "A-605"
    },
    {
      "id": "s-14",
      "edge": "e-44",
      "t": 0.941,
      "side": 1,
      "flat": "A-106"
    },
    {
      "id": "s-15",
      "edge": "e-94",
      "t": 0.002,
      "side": -1,
      "flat": "A-1204"
    },
    {
      "id": "s-16",
      "edge": "e-42",
      "t": 0.395,
      "side": -1,
      "flat": "B-401"
    },
    {
      "id": "s-17",
      "edge": "e-93",
      "t": 0.945,
      "side": 1,
      "flat": "A-1401"
    },
    {
      "id": "s-18",
      "edge": "e-52",
      "t": 0.248,
      "side": 1,
      "flat": "A-305"
    },
    {
      "id": "s-19",
      "edge": "e-45",
      "t": 0.804,
      "side": -1,
      "flat": "A-1205"
    },
    {
      "id": "s-20",
      "edge": "e-94",
      "t": 0.519,
      "side": -1,
      "flat": "A-1002"
    },
    {
      "id": "s-21",
      "edge": "e-109",
      "t": 0.272,
      "side": 1,
      "flat": "A-307"
    },
    {
      "id": "s-22",
      "edge": "e-43",
      "t": 0.387,
      "side": 1,
      "flat": "A-1107"
    },
    {
      "id": "s-23",
      "edge": "e-93",
      "t": 0.632,
      "side": 1,
      "flat": "A-206"
    },
    {
      "id": "s-24",
      "edge": "e-93",
      "t": 0.405,
      "side": -1,
      "flat": "B-902"
    },
    {
      "id": "s-25",
      "edge": "e-109",
      "t": 0.464,
      "side": 1,
      "flat": "A-1306"
    },
    {
      "id": "s-26",
      "edge": "e-42",
      "t": 0.822,
      "side": 1,
      "flat": "A-1008"
    },
    {
      "id": "s-27",
      "edge": "e-44",
      "t": 0.232,
      "side": 1,
      "flat": "A-205"
    },
    {
      "id": "s-28",
      "edge": "e-47",
      "t": 0.657,
      "side": -1,
      "flat": "A-401"
    },
    {
      "id": "s-29",
      "edge": "e-94",
      "t": 0.069,
      "side": -1,
      "flat": "A-204"
    },
    {
      "id": "s-30",
      "edge": "e-94",
      "t": 0.267,
      "side": 1,
      "flat": "A-505"
    },
    {
      "id": "s-31",
      "edge": "e-42",
      "t": 1,
      "side": 1,
      "flat": "A-705"
    },
    {
      "id": "s-32",
      "edge": "e-42",
      "t": 0.572,
      "side": 1,
      "flat": "A-G1"
    },
    {
      "id": "s-33",
      "edge": "e-42",
      "t": 0.799,
      "side": 1,
      "flat": "A-506"
    },
    {
      "id": "s-34",
      "edge": "e-32",
      "t": 1,
      "side": 1,
      "flat": "A-606"
    },
    {
      "id": "s-35",
      "edge": "e-32",
      "t": 1,
      "side": 1,
      "flat": "A-105"
    },
    {
      "id": "s-36",
      "edge": "e-91",
      "t": 0.196,
      "side": -1,
      "flat": "B-802"
    },
    {
      "id": "s-37",
      "edge": "e-91",
      "t": 0.07,
      "side": -1,
      "flat": "C-203"
    },
    {
      "id": "s-38",
      "edge": "e-96",
      "t": 0.213,
      "side": -1,
      "flat": "B-301"
    },
    {
      "id": "s-39",
      "edge": "e-91",
      "t": 0.527,
      "side": -1,
      "flat": "B-504"
    },
    {
      "id": "s-40",
      "edge": "e-91",
      "t": 0.255,
      "side": -1,
      "flat": "B-1205"
    },
    {
      "id": "s-41",
      "edge": "e-96",
      "t": 0.152,
      "side": -1,
      "flat": "B-405"
    },
    {
      "id": "s-42",
      "edge": "e-91",
      "t": 0.954,
      "side": -1,
      "flat": "B-503"
    },
    {
      "id": "s-43",
      "edge": "e-90",
      "t": 0.402,
      "side": -1,
      "flat": "C-405"
    },
    {
      "id": "s-44",
      "edge": "e-91",
      "t": 0.925,
      "side": -1,
      "flat": "B-1101"
    },
    {
      "id": "s-45",
      "edge": "e-29",
      "t": 0.512,
      "side": 1,
      "flat": "D-803"
    },
    {
      "id": "s-46",
      "edge": "e-35",
      "t": 0.079,
      "side": 1,
      "flat": "C-202"
    },
    {
      "id": "s-47",
      "edge": "e-39",
      "t": 0.2,
      "side": -1,
      "flat": "B-1004"
    },
    {
      "id": "s-48",
      "edge": "e-29",
      "t": 0.425,
      "side": -1,
      "flat": "D-202"
    },
    {
      "id": "s-49",
      "edge": "e-32",
      "t": 0.739,
      "side": -1,
      "flat": "B-804"
    },
    {
      "id": "s-50",
      "edge": "e-38",
      "t": 0.776,
      "side": -1,
      "flat": "B-1302"
    },
    {
      "id": "s-51",
      "edge": "e-29",
      "t": 0.33,
      "side": -1,
      "flat": "D-G6"
    },
    {
      "id": "s-52",
      "edge": "e-29",
      "t": 0.6,
      "side": -1,
      "flat": "D-806"
    },
    {
      "id": "s-53",
      "edge": "e-29",
      "t": 0.763,
      "side": 1,
      "flat": "D-106"
    },
    {
      "id": "s-54",
      "edge": "e-29",
      "t": 0.75,
      "side": 1,
      "flat": "B-803"
    },
    {
      "id": "s-55",
      "edge": "e-35",
      "t": 0.477,
      "side": -1,
      "flat": "C-1304"
    },
    {
      "id": "s-56",
      "edge": "e-34",
      "t": 0.443,
      "side": 1,
      "flat": "C-402"
    },
    {
      "id": "s-57",
      "edge": "e-33",
      "t": 0.767,
      "side": -1,
      "flat": "C-1303"
    },
    {
      "id": "s-58",
      "edge": "e-33",
      "t": 0.126,
      "side": -1,
      "flat": "D-401"
    },
    {
      "id": "s-59",
      "edge": "e-22",
      "t": 0.401,
      "side": 1,
      "flat": "F-1301"
    },
    {
      "id": "s-60",
      "edge": "e-30",
      "t": 0.576,
      "side": -1,
      "flat": "D-304"
    },
    {
      "id": "s-61",
      "edge": "e-31",
      "t": 0.269,
      "side": -1,
      "flat": "D-301"
    },
    {
      "id": "s-62",
      "edge": "e-32",
      "t": 0.86,
      "side": 1,
      "flat": "F-602"
    },
    {
      "id": "s-63",
      "edge": "e-22",
      "t": 0.336,
      "side": -1,
      "flat": "E-1301"
    },
    {
      "id": "s-64",
      "edge": "e-23",
      "t": 0.463,
      "side": -1,
      "flat": "F-1101"
    },
    {
      "id": "s-65",
      "edge": "e-27",
      "t": 0.885,
      "side": 1,
      "flat": "F-204"
    },
    {
      "id": "s-66",
      "edge": "e-22",
      "t": 0.536,
      "side": 1,
      "flat": "F-502"
    },
    {
      "id": "s-67",
      "edge": "e-27",
      "t": 0.813,
      "side": -1,
      "flat": "F-1302"
    },
    {
      "id": "s-68",
      "edge": "e-27",
      "t": 0.814,
      "side": 1,
      "flat": "F-202"
    },
    {
      "id": "s-69",
      "edge": "e-27",
      "t": 0.506,
      "side": 1,
      "flat": "F-1101"
    },
    {
      "id": "s-70",
      "edge": "e-22",
      "t": 0.667,
      "side": 1,
      "flat": "F-302"
    },
    {
      "id": "s-71",
      "edge": "e-22",
      "t": 0.702,
      "side": 1,
      "flat": "F-402"
    },
    {
      "id": "s-72",
      "edge": "e-31",
      "t": 0.303,
      "side": 1,
      "flat": "D-1204"
    },
    {
      "id": "s-73",
      "edge": "e-27",
      "t": 0.193,
      "side": 1,
      "flat": "F-304"
    },
    {
      "id": "s-74",
      "edge": "e-22",
      "t": 0.739,
      "side": -1,
      "flat": "F-904"
    },
    {
      "id": "s-75",
      "edge": "e-27",
      "t": 0.646,
      "side": -1,
      "flat": "F-1102"
    },
    {
      "id": "s-76",
      "edge": "e-22",
      "t": 0.756,
      "side": 1,
      "flat": "F-105"
    },
    {
      "id": "s-77",
      "edge": "e-32",
      "t": 0.614,
      "side": 1,
      "flat": "A-1108"
    },
    {
      "id": "s-78",
      "edge": "e-27",
      "t": 0.573,
      "side": 1,
      "flat": "F-703"
    },
    {
      "id": "s-79",
      "edge": "e-27",
      "t": 0.487,
      "side": 1,
      "flat": "F-501"
    },
    {
      "id": "s-80",
      "edge": "e-27",
      "t": 0.283,
      "side": -1,
      "flat": "F-304"
    },
    {
      "id": "s-81",
      "edge": "e-22",
      "t": 0.541,
      "side": -1,
      "flat": "F-702"
    },
    {
      "id": "s-82",
      "edge": "e-27",
      "t": 0.303,
      "side": -1,
      "flat": "F-901"
    },
    {
      "id": "s-83",
      "edge": "e-27",
      "t": 0.27,
      "side": 1,
      "flat": "F-505"
    },
    {
      "id": "s-84",
      "edge": "e-32",
      "t": 0.971,
      "side": 1,
      "flat": "F-203"
    },
    {
      "id": "s-85",
      "edge": "e-22",
      "t": 0.156,
      "side": -1,
      "flat": "E-1202"
    },
    {
      "id": "s-86",
      "edge": "e-27",
      "t": 0.969,
      "side": 1,
      "flat": "F-804"
    },
    {
      "id": "s-87",
      "edge": "e-32",
      "t": 0.447,
      "side": 1,
      "flat": "D-101"
    },
    {
      "id": "s-88",
      "edge": "e-27",
      "t": 0.692,
      "side": 1,
      "flat": "F-201"
    },
    {
      "id": "s-89",
      "edge": "e-27",
      "t": 0.923,
      "side": 1,
      "flat": "F-205"
    },
    {
      "id": "s-90",
      "edge": "e-30",
      "t": 0.725,
      "side": 1,
      "flat": "E-405"
    },
    {
      "id": "s-91",
      "edge": "e-27",
      "t": 0.406,
      "side": 1,
      "flat": "F-1102"
    },
    {
      "id": "s-92",
      "edge": "e-32",
      "t": 0.272,
      "side": 1,
      "flat": "B-405"
    },
    {
      "id": "s-93",
      "edge": "e-32",
      "t": 0.811,
      "side": 1,
      "flat": "F-203"
    },
    {
      "id": "s-94",
      "edge": "e-22",
      "t": 0.078,
      "side": 1,
      "flat": "E-1001"
    },
    {
      "id": "s-96",
      "edge": "e-25",
      "t": 0.638,
      "side": 1,
      "flat": "E-102"
    },
    {
      "id": "s-97",
      "edge": "e-25",
      "t": 0.103,
      "side": 1,
      "flat": "F-1402"
    },
    {
      "id": "s-98",
      "edge": "e-25",
      "t": 0.988,
      "side": 1,
      "flat": "F-G5"
    },
    {
      "id": "s-99",
      "edge": "e-25",
      "t": 0.521,
      "side": 1,
      "flat": "F-G2"
    },
    {
      "id": "s-100",
      "edge": "e-25",
      "t": 0.844,
      "side": -1,
      "flat": "F-301"
    },
    {
      "id": "s-101",
      "edge": "e-25",
      "t": 0.355,
      "side": 1,
      "flat": "F-1402"
    },
    {
      "id": "s-102",
      "edge": "e-25",
      "t": 0.656,
      "side": 1,
      "flat": "F-G4"
    },
    {
      "id": "s-103",
      "edge": "e-26",
      "t": 1,
      "side": 1,
      "flat": "F-401"
    },
    {
      "id": "s-104",
      "edge": "e-25",
      "t": 0.919,
      "side": 1,
      "flat": "F-404"
    },
    {
      "id": "s-105",
      "edge": "e-25",
      "t": 1,
      "side": 1,
      "flat": "F-402"
    },
    {
      "id": "s-106",
      "edge": "e-25",
      "t": 1,
      "side": 1,
      "flat": "F-803"
    },
    {
      "id": "s-107",
      "edge": "e-87",
      "t": 0.083,
      "side": 1,
      "flat": "F-1304"
    },
    {
      "id": "s-108",
      "edge": "e-27",
      "t": 0.079,
      "side": 1,
      "flat": "F-704"
    },
    {
      "id": "s-109",
      "edge": "e-27",
      "t": 0.089,
      "side": -1,
      "flat": "F-101"
    },
    {
      "id": "s-110",
      "edge": "e-25",
      "t": 0.496,
      "side": -1,
      "flat": "F-405"
    },
    {
      "id": "s-111",
      "edge": "e-25",
      "t": 1,
      "side": 1,
      "flat": "F-801"
    },
    {
      "id": "s-112",
      "edge": "e-85",
      "t": 0.568,
      "side": -1,
      "flat": "C-1001"
    },
    {
      "id": "s-113",
      "edge": "e-85",
      "t": 0.758,
      "side": -1,
      "flat": "C-801"
    },
    {
      "id": "s-114",
      "edge": "e-85",
      "t": 0.269,
      "side": -1,
      "flat": "C-1202"
    },
    {
      "id": "s-115",
      "edge": "e-84",
      "t": 0.685,
      "side": -1,
      "flat": "C-801"
    },
    {
      "id": "s-116",
      "edge": "e-85",
      "t": 0.969,
      "side": -1,
      "flat": "C-504"
    },
    {
      "id": "s-117",
      "edge": "e-85",
      "t": 0.756,
      "side": -1,
      "flat": "C-605"
    },
    {
      "id": "s-118",
      "edge": "e-8",
      "t": 0.335,
      "side": 1,
      "flat": "D-204"
    },
    {
      "id": "s-119",
      "edge": "e-82",
      "t": 0.706,
      "side": 1,
      "flat": "D-1104"
    },
    {
      "id": "s-120",
      "edge": "e-18",
      "t": 0.342,
      "side": -1,
      "flat": "D-505"
    },
    {
      "id": "s-121",
      "edge": "e-8",
      "t": 0,
      "side": 1,
      "flat": "D-501"
    },
    {
      "id": "s-122",
      "edge": "e-18",
      "t": 0.648,
      "side": -1,
      "flat": "D-1302"
    },
    {
      "id": "s-123",
      "edge": "e-18",
      "t": 0.187,
      "side": 1,
      "flat": "D-1103"
    },
    {
      "id": "s-124",
      "edge": "e-9",
      "t": 0.521,
      "side": -1,
      "flat": "C-803"
    },
    {
      "id": "s-125",
      "edge": "e-4",
      "t": 0.332,
      "side": 1,
      "flat": "D-1106"
    },
    {
      "id": "s-126",
      "edge": "e-9",
      "t": 0.203,
      "side": -1,
      "flat": "C-602"
    },
    {
      "id": "s-127",
      "edge": "e-9",
      "t": 0.156,
      "side": 1,
      "flat": "D-1302"
    },
    {
      "id": "s-128",
      "edge": "e-4",
      "t": 0.827,
      "side": 1,
      "flat": "D-1002"
    },
    {
      "id": "s-129",
      "edge": "e-81",
      "t": 0.134,
      "side": 1,
      "flat": "D-902"
    },
    {
      "id": "s-130",
      "edge": "e-4",
      "t": 0.586,
      "side": 1,
      "flat": "D-1005"
    },
    {
      "id": "s-131",
      "edge": "e-19",
      "t": 0.537,
      "side": -1,
      "flat": "C-1201"
    },
    {
      "id": "s-132",
      "edge": "e-18",
      "t": 0.773,
      "side": -1,
      "flat": "D-901"
    },
    {
      "id": "s-133",
      "edge": "e-4",
      "t": 0.711,
      "side": 1,
      "flat": "D-1002"
    },
    {
      "id": "s-134",
      "edge": "e-88",
      "t": 0.234,
      "side": -1,
      "flat": "F-504"
    },
    {
      "id": "s-135",
      "edge": "e-15",
      "t": 0.701,
      "side": -1,
      "flat": "E-302"
    },
    {
      "id": "s-136",
      "edge": "e-15",
      "t": 0.852,
      "side": -1,
      "flat": "E-1002"
    },
    {
      "id": "s-137",
      "edge": "e-11",
      "t": 0.234,
      "side": 1,
      "flat": "D-102"
    },
    {
      "id": "s-138",
      "edge": "e-17",
      "t": 0.287,
      "side": -1,
      "flat": "E-802"
    },
    {
      "id": "s-139",
      "edge": "e-11",
      "t": 0.719,
      "side": 1,
      "flat": "D-201"
    },
    {
      "id": "s-140",
      "edge": "e-11",
      "t": 0.492,
      "side": 1,
      "flat": "D-703"
    },
    {
      "id": "s-141",
      "edge": "e-30",
      "t": 0.234,
      "side": 1,
      "flat": "D-801"
    },
    {
      "id": "s-142",
      "edge": "e-88",
      "t": 0.614,
      "side": 1,
      "flat": "F-503"
    },
    {
      "id": "s-143",
      "edge": "e-88",
      "t": 0.511,
      "side": -1,
      "flat": "F-1103"
    },
    {
      "id": "s-144",
      "edge": "e-11",
      "t": 0.892,
      "side": 1,
      "flat": "D-1003"
    },
    {
      "id": "s-145",
      "edge": "e-79",
      "t": 0.34,
      "side": 1,
      "flat": "E-804"
    },
    {
      "id": "s-146",
      "edge": "e-15",
      "t": 0.406,
      "side": -1,
      "flat": "E-404"
    },
    {
      "id": "s-147",
      "edge": "e-15",
      "t": 0.221,
      "side": -1,
      "flat": "E-704"
    },
    {
      "id": "s-148",
      "edge": "e-15",
      "t": 0.541,
      "side": -1,
      "flat": "E-1004"
    },
    {
      "id": "s-149",
      "edge": "e-17",
      "t": 0.617,
      "side": 1,
      "flat": "E-805"
    },
    {
      "id": "s-150",
      "edge": "e-12",
      "t": 0.74,
      "side": 1,
      "flat": "D-801"
    },
    {
      "id": "s-151",
      "edge": "e-88",
      "t": 0.799,
      "side": -1,
      "flat": "E-304"
    },
    {
      "id": "s-152",
      "edge": "e-30",
      "t": 0.681,
      "side": -1,
      "flat": "D-304"
    },
    {
      "id": "s-153",
      "edge": "e-1",
      "t": 1,
      "side": -1,
      "flat": "E-903"
    },
    {
      "id": "s-154",
      "edge": "e-14",
      "t": 0.695,
      "side": 1,
      "flat": "E-1102"
    },
    {
      "id": "s-155",
      "edge": "e-14",
      "t": 0.695,
      "side": 1,
      "flat": "E-604"
    },
    {
      "id": "s-156",
      "edge": "e-13",
      "t": 0.784,
      "side": 1,
      "flat": "E-901"
    },
    {
      "id": "s-157",
      "edge": "e-24",
      "t": 1,
      "side": 1,
      "flat": "F-102"
    },
    {
      "id": "s-158",
      "edge": "e-1",
      "t": 0.729,
      "side": -1,
      "flat": "E-1305"
    },
    {
      "id": "s-159",
      "edge": "e-1",
      "t": 0.181,
      "side": -1,
      "flat": "E-G2"
    },
    {
      "id": "s-160",
      "edge": "e-13",
      "t": 0.453,
      "side": 1,
      "flat": "E-204"
    },
    {
      "id": "s-161",
      "edge": "e-13",
      "t": 0.401,
      "side": 1,
      "flat": "E-1104"
    },
    {
      "id": "s-162",
      "edge": "e-1",
      "t": 0.111,
      "side": -1,
      "flat": "E-504"
    },
    {
      "id": "s-163",
      "edge": "e-4",
      "t": 0.623,
      "side": -1,
      "flat": "D-402"
    },
    {
      "id": "s-164",
      "edge": "e-5",
      "t": 0,
      "side": -1,
      "flat": "D-602"
    },
    {
      "id": "s-165",
      "edge": "e-5",
      "t": 0.804,
      "side": 1,
      "flat": "C-805"
    },
    {
      "id": "s-166",
      "edge": "e-5",
      "t": 0.486,
      "side": -1,
      "flat": "C-1205"
    },
    {
      "id": "s-167",
      "edge": "e-4",
      "t": 0.432,
      "side": -1,
      "flat": "D-302"
    },
    {
      "id": "s-168",
      "edge": "e-5",
      "t": 0.411,
      "side": -1,
      "flat": "E-502"
    },
    {
      "id": "s-169",
      "edge": "e-79",
      "t": 0.095,
      "side": -1,
      "flat": "E-1304"
    },
    {
      "id": "s-170",
      "edge": "e-79",
      "t": 0.445,
      "side": -1,
      "flat": "E-505"
    },
    {
      "id": "s-171",
      "edge": "e-4",
      "t": 0.247,
      "side": -1,
      "flat": "D-904"
    },
    {
      "id": "s-172",
      "edge": "e-79",
      "t": 0.248,
      "side": -1,
      "flat": "E-902"
    },
    {
      "id": "s-173",
      "edge": "e-79",
      "t": 0.772,
      "side": -1,
      "flat": "E-503"
    },
    {
      "id": "s-174",
      "edge": "e-79",
      "t": 0.946,
      "side": -1,
      "flat": "E-803"
    },
    {
      "id": "s-175",
      "edge": "e-79",
      "t": 0.603,
      "side": -1,
      "flat": "E-402"
    },
    {
      "id": "s-176",
      "edge": "e-78",
      "t": 0.848,
      "side": -1,
      "flat": "E-904"
    },
    {
      "id": "s-177",
      "edge": "e-4",
      "t": 0.086,
      "side": -1,
      "flat": "D-701"
    },
    {
      "id": "s-178",
      "edge": "e-78",
      "t": 0.002,
      "side": -1,
      "flat": "E-1103"
    },
    {
      "id": "s-179",
      "edge": "e-78",
      "t": 0.002,
      "side": -1,
      "flat": "E-603"
    },
    {
      "id": "s-180",
      "edge": "e-67",
      "t": 0.712,
      "side": 1,
      "flat": "A-406"
    },
    {
      "id": "s-181",
      "edge": "e-61",
      "t": 0.321,
      "side": 1,
      "flat": "A-1506"
    },
    {
      "id": "s-182",
      "edge": "e-61",
      "t": 0.14,
      "side": 1,
      "flat": "A-704"
    },
    {
      "id": "s-183",
      "edge": "e-67",
      "t": 0.369,
      "side": 1,
      "flat": "A-208"
    },
    {
      "id": "s-184",
      "edge": "e-106",
      "t": 0.152,
      "side": 1,
      "flat": "A-708"
    },
    {
      "id": "s-185",
      "edge": "e-67",
      "t": 0.942,
      "side": 1,
      "flat": "A-804"
    },
    {
      "id": "s-186",
      "edge": "e-61",
      "t": 0.621,
      "side": 1,
      "flat": "A-701"
    },
    {
      "id": "s-187",
      "edge": "e-61",
      "t": 0.422,
      "side": -1,
      "flat": "A-1207"
    },
    {
      "id": "s-188",
      "edge": "e-61",
      "t": 0.046,
      "side": -1,
      "flat": "A-807"
    },
    {
      "id": "s-189",
      "edge": "e-68",
      "t": 0.265,
      "side": 1,
      "flat": "A-803"
    },
    {
      "id": "s-190",
      "edge": "e-106",
      "t": 0.373,
      "side": 1,
      "flat": "A-603"
    },
    {
      "id": "s-191",
      "edge": "e-60",
      "t": 0.874,
      "side": 1,
      "flat": "A-1106"
    },
    {
      "id": "s-192",
      "edge": "e-68",
      "t": 0.973,
      "side": 1,
      "flat": "A-207"
    },
    {
      "id": "s-193",
      "edge": "e-68",
      "t": 0.607,
      "side": 1,
      "flat": "A-404"
    },
    {
      "id": "s-194",
      "edge": "e-61",
      "t": 0.62,
      "side": -1,
      "flat": "A-705"
    },
    {
      "id": "s-195",
      "edge": "e-64",
      "t": 0.939,
      "side": -1,
      "flat": "A-901"
    },
    {
      "id": "s-196",
      "edge": "e-73",
      "t": 0.172,
      "side": 1,
      "flat": "A-607"
    },
    {
      "id": "s-197",
      "edge": "e-77",
      "t": 0.961,
      "side": -1,
      "flat": "A-1304"
    },
    {
      "id": "s-198",
      "edge": "e-68",
      "t": 0.55,
      "side": -1,
      "flat": "A-1004"
    },
    {
      "id": "s-199",
      "edge": "e-73",
      "t": 0.843,
      "side": 1,
      "flat": "A-1502"
    },
    {
      "id": "s-200",
      "edge": "e-69",
      "t": 0.819,
      "side": 1,
      "flat": "A-904"
    },
    {
      "id": "s-201",
      "edge": "e-77",
      "t": 0.544,
      "side": -1,
      "flat": "A-1504"
    },
    {
      "id": "s-202",
      "edge": "e-72",
      "t": 0.84,
      "side": 1,
      "flat": "A-1501"
    },
    {
      "id": "s-203",
      "edge": "e-69",
      "t": 0.701,
      "side": -1,
      "flat": "A-902"
    },
    {
      "id": "s-204",
      "edge": "e-69",
      "t": 0.292,
      "side": 1,
      "flat": "A-202"
    },
    {
      "id": "s-205",
      "edge": "e-71",
      "t": 0.296,
      "side": -1,
      "flat": "A-1404"
    },
    {
      "id": "s-206",
      "edge": "e-77",
      "t": 0.348,
      "side": -1,
      "flat": "A-903"
    },
    {
      "id": "s-207",
      "edge": "e-73",
      "t": 0.67,
      "side": 1,
      "flat": "A-1003"
    },
    {
      "id": "s-208",
      "edge": "e-66",
      "t": 0.239,
      "side": -1,
      "flat": "A-901"
    },
    {
      "id": "s-209",
      "edge": "e-74",
      "t": 0.631,
      "side": -1,
      "flat": "A-907"
    },
    {
      "id": "s-210",
      "edge": "e-70",
      "t": 1,
      "side": 1,
      "flat": "A-1007"
    },
    {
      "id": "s-211",
      "edge": "e-63",
      "t": 0.285,
      "side": -1,
      "flat": "A-1208"
    },
    {
      "id": "s-212",
      "edge": "e-75",
      "t": 0.385,
      "side": 1,
      "flat": "A-1507"
    },
    {
      "id": "s-213",
      "edge": "e-70",
      "t": 0.248,
      "side": 1,
      "flat": "A-1508"
    },
    {
      "id": "s-214",
      "edge": "e-63",
      "t": 0.443,
      "side": -1,
      "flat": "A-1106"
    },
    {
      "id": "s-215",
      "edge": "e-75",
      "t": 0.784,
      "side": 1,
      "flat": "A-1504"
    }
  ]
};
