/* GENERATED by the publish backend. Do not hand-edit - the next publish overwrites it. */
const MAP = {
  "community": "Aditya Athena",
  "view": {
    "w": 1000,
    "h": 1396
  },
  "levels": [
    {
      "id": "G",
      "name": "Ground",
      "underground": false
    },
    {
      "id": "P1",
      "name": "A Block B1",
      "underground": true,
      "image": "plans/athena-lg.png",
      "imageBox": [
        0,
        0,
        1100,
        762
      ]
    },
    {
      "id": "P2",
      "name": "Basement 1 (A Block B2)",
      "underground": true,
      "image": "plans/athena-map.png",
      "imageBox": [
        0,
        0,
        1000,
        1396
      ]
    }
  ],
  "blocks": [
    {
      "id": "A",
      "name": "Block A",
      "lobby": "lift-a",
      "floors": 15,
      "perFloor": 8,
      "ground": 8
    },
    {
      "id": "B",
      "name": "Block B",
      "lobby": "lift-b",
      "floors": 15,
      "perFloor": 5,
      "ground": 5
    },
    {
      "id": "C",
      "name": "Block C",
      "lobby": "lift-c",
      "floors": 14,
      "perFloor": 5,
      "ground": 5
    },
    {
      "id": "D",
      "name": "Block D",
      "lobby": "lift-d",
      "floors": 14,
      "perFloor": 6,
      "ground": 6
    },
    {
      "id": "E",
      "name": "Block E",
      "lobby": "lift-e",
      "floors": 14,
      "perFloor": 5,
      "ground": 5
    },
    {
      "id": "F",
      "name": "Block F",
      "lobby": "lift-f",
      "floors": 14,
      "perFloor": 5,
      "ground": 5
    }
  ],
  "slotRuns": [],
  "allotments": [],
  "areas": [
    {
      "id": "core-e",
      "level": "P2",
      "node": "lift-e",
      "name": "Block E",
      "points": [
        [
          190,
          110
        ],
        [
          350,
          110
        ],
        [
          350,
          240
        ],
        [
          190,
          240
        ]
      ]
    },
    {
      "id": "core-d",
      "level": "P2",
      "node": "lift-d",
      "name": "Block D",
      "points": [
        [
          470,
          110
        ],
        [
          640,
          110
        ],
        [
          640,
          300
        ],
        [
          470,
          300
        ]
      ]
    },
    {
      "id": "core-c",
      "level": "P2",
      "node": "lift-c",
      "name": "Block C",
      "points": [
        [
          690,
          80
        ],
        [
          840,
          80
        ],
        [
          840,
          320
        ],
        [
          690,
          320
        ]
      ]
    },
    {
      "id": "core-f",
      "level": "P2",
      "node": "lift-f",
      "name": "Block F",
      "points": [
        [
          120,
          355
        ],
        [
          340,
          355
        ],
        [
          340,
          530
        ],
        [
          120,
          530
        ]
      ]
    },
    {
      "id": "core-b",
      "level": "P2",
      "node": "lift-b",
      "name": "Block B",
      "points": [
        [
          700,
          370
        ],
        [
          840,
          370
        ],
        [
          840,
          650
        ],
        [
          700,
          650
        ]
      ]
    },
    {
      "id": "core-a",
      "level": "P2",
      "node": "lift-a",
      "name": "Block A",
      "points": [
        [
          550,
          690
        ],
        [
          690,
          690
        ],
        [
          690,
          920
        ],
        [
          550,
          920
        ]
      ]
    },
    {
      "id": "core-a2",
      "level": "P2",
      "node": "lift-a2",
      "name": "Block A (east)",
      "points": [
        [
          710,
          690
        ],
        [
          850,
          690
        ],
        [
          850,
          940
        ],
        [
          710,
          940
        ]
      ]
    },
    {
      "id": "visitor-area",
      "level": "P2",
      "node": "visitor",
      "name": "Visitor Parking",
      "points": [
        [
          665,
          1200
        ],
        [
          815,
          1200
        ],
        [
          815,
          1345
        ],
        [
          665,
          1345
        ]
      ]
    }
  ],
  "nodes": [
    {
      "id": "gate",
      "level": "G",
      "xy": [
        100,
        560
      ],
      "name": "Main Gate",
      "cat": "entry",
      "dest": true,
      "anchor": true
    },
    {
      "id": "lift-e",
      "level": "P2",
      "xy": [
        283.7,
        143.9
      ],
      "name": "Block E Lift",
      "cat": "block",
      "dest": true,
      "anchor": true,
      "lift": true
    },
    {
      "id": "lift-d",
      "level": "P2",
      "xy": [
        553.3,
        200.8
      ],
      "name": "Block D Lift",
      "cat": "block",
      "dest": true,
      "anchor": true,
      "lift": true
    },
    {
      "id": "lift-c",
      "level": "P2",
      "xy": [
        802.1,
        174.2
      ],
      "name": "Block C Lift",
      "cat": "block",
      "dest": true,
      "anchor": true,
      "lift": true
    },
    {
      "id": "lift-f",
      "level": "P2",
      "xy": [
        226.9,
        384.5
      ],
      "name": "Block F Lift",
      "cat": "block",
      "dest": true,
      "anchor": true,
      "lift": true
    },
    {
      "id": "lift-b",
      "level": "P2",
      "xy": [
        775,
        505
      ],
      "name": "Block B Lift",
      "cat": "block",
      "dest": true,
      "anchor": true,
      "lift": true
    },
    {
      "id": "lift-a",
      "level": "P2",
      "xy": [
        663.2,
        856.1
      ],
      "name": "Block A Lift",
      "cat": "block",
      "dest": true,
      "anchor": true,
      "lift": true
    },
    {
      "id": "lift-a2",
      "level": "P2",
      "xy": [
        790.1,
        849.2
      ],
      "name": "Block A Lift (east)",
      "cat": "block",
      "dest": true,
      "anchor": true,
      "lift": true
    },
    {
      "id": "visitor",
      "level": "P2",
      "xy": [
        698.1,
        1256.3
      ],
      "name": "Visitor Parking",
      "cat": "parking",
      "dest": true,
      "anchor": true
    },
    {
      "id": "g-forecourt",
      "level": "G",
      "xy": [
        100,
        440
      ],
      "name": "Block A forecourt"
    },
    {
      "id": "g-apron",
      "level": "G",
      "xy": [
        100,
        320
      ],
      "name": "Concrete apron by Block A"
    },
    {
      "id": "g-bend",
      "level": "G",
      "xy": [
        330,
        320
      ],
      "name": "Road along the boundary wall"
    },
    {
      "id": "g-guard",
      "level": "G",
      "xy": [
        520,
        400
      ],
      "name": "Guard post"
    },
    {
      "id": "g-main-ramp",
      "level": "G",
      "xy": [
        470,
        470
      ],
      "name": "Basement entry ramp"
    },
    {
      "id": "g-a-ramp",
      "level": "G",
      "xy": [
        -60,
        300
      ],
      "name": "Block A ramp (pergola)"
    },
    {
      "id": "main-ramp-foot",
      "level": "P2",
      "xy": [
        640,
        636
      ],
      "name": "Foot of the entry ramp",
      "cat": "entry",
      "anchor": true
    },
    {
      "id": "a-ramp-foot",
      "level": "P1",
      "xy": [
        398,
        301
      ],
      "name": "Foot of the Block A ramp",
      "cat": "entry"
    },
    {
      "id": "a2-ramp-top",
      "level": "P1",
      "xy": [
        590,
        301
      ],
      "name": "Top of the ramp down to Basement 1"
    },
    {
      "id": "a2-ramp-foot",
      "level": "P2",
      "xy": [
        623,
        1178
      ],
      "name": "Foot of the ramp from Block A"
    },
    {
      "id": "p2-1",
      "level": "P2",
      "xy": [
        160,
        175
      ]
    },
    {
      "id": "p2-2",
      "level": "P2",
      "xy": [
        160,
        104
      ]
    },
    {
      "id": "p2-3",
      "level": "P2",
      "xy": [
        175,
        95
      ]
    },
    {
      "id": "p2-4",
      "level": "P2",
      "xy": [
        449,
        95
      ]
    },
    {
      "id": "p2-5",
      "level": "P2",
      "xy": [
        656,
        90
      ]
    },
    {
      "id": "p2-6",
      "level": "P2",
      "xy": [
        656,
        66
      ]
    },
    {
      "id": "p2-7",
      "level": "P2",
      "xy": [
        836,
        66
      ]
    },
    {
      "id": "p2-8",
      "level": "P2",
      "xy": [
        656,
        220
      ]
    },
    {
      "id": "p2-9",
      "level": "P2",
      "xy": [
        676,
        262
      ]
    },
    {
      "id": "p2-10",
      "level": "P2",
      "xy": [
        679,
        337
      ]
    },
    {
      "id": "p2-11",
      "level": "P2",
      "xy": [
        846,
        340
      ]
    },
    {
      "id": "p2-12",
      "level": "P2",
      "xy": [
        438,
        264
      ]
    },
    {
      "id": "p2-13",
      "level": "P2",
      "xy": [
        452,
        335
      ]
    },
    {
      "id": "p2-14",
      "level": "P2",
      "xy": [
        158,
        262
      ]
    },
    {
      "id": "p2-15",
      "level": "P2",
      "xy": [
        107,
        341
      ]
    },
    {
      "id": "p2-16",
      "level": "P2",
      "xy": [
        367,
        336
      ]
    },
    {
      "id": "p2-17",
      "level": "P2",
      "xy": [
        851,
        682
      ]
    },
    {
      "id": "p2-18",
      "level": "P2",
      "xy": [
        856,
        957
      ]
    },
    {
      "id": "p2-19",
      "level": "P2",
      "xy": [
        368,
        528
      ]
    },
    {
      "id": "p2-20",
      "level": "P2",
      "xy": [
        387,
        540
      ]
    },
    {
      "id": "p2-21",
      "level": "P2",
      "xy": [
        81,
        358
      ]
    },
    {
      "id": "p2-22",
      "level": "P2",
      "xy": [
        83,
        515
      ]
    },
    {
      "id": "p2-23",
      "level": "P2",
      "xy": [
        105,
        532
      ]
    },
    {
      "id": "p2-24",
      "level": "P2",
      "xy": [
        464,
        540
      ]
    },
    {
      "id": "p2-25",
      "level": "P2",
      "xy": [
        680,
        536
      ]
    },
    {
      "id": "p2-26",
      "level": "P2",
      "xy": [
        464,
        422
      ]
    },
    {
      "id": "p2-27",
      "level": "P2",
      "xy": [
        474,
        667
      ]
    },
    {
      "id": "p2-28",
      "level": "P2",
      "xy": [
        679,
        418
      ]
    },
    {
      "id": "p2-29",
      "level": "P2",
      "xy": [
        698,
        689
      ]
    },
    {
      "id": "p2-30",
      "level": "P2",
      "xy": [
        709,
        968
      ]
    },
    {
      "id": "p2-31",
      "level": "P2",
      "xy": [
        538,
        677
      ]
    },
    {
      "id": "p2-32",
      "level": "P2",
      "xy": [
        622,
        669
      ]
    },
    {
      "id": "p2-33",
      "level": "P2",
      "xy": [
        546,
        855
      ]
    },
    {
      "id": "p2-34",
      "level": "P2",
      "xy": [
        600,
        919
      ]
    },
    {
      "id": "p2-35",
      "level": "P2",
      "xy": [
        620,
        964
      ]
    },
    {
      "id": "p2-36",
      "level": "P2",
      "xy": [
        680,
        971
      ]
    },
    {
      "id": "p2-37",
      "level": "P2",
      "xy": [
        765,
        971
      ]
    },
    {
      "id": "p2-38",
      "level": "P2",
      "xy": [
        891,
        965
      ]
    },
    {
      "id": "p2-39",
      "level": "P2",
      "xy": [
        680,
        1200
      ]
    },
    {
      "id": "p2-40",
      "level": "P2",
      "xy": [
        680,
        1335
      ]
    },
    {
      "id": "p2-41",
      "level": "P2",
      "xy": [
        765,
        1200
      ]
    },
    {
      "id": "p2-42",
      "level": "P2",
      "xy": [
        770,
        1290
      ]
    },
    {
      "id": "p2-43",
      "level": "P2",
      "xy": [
        797,
        1300
      ]
    },
    {
      "id": "p2-44",
      "level": "P2",
      "xy": [
        799,
        1334
      ]
    },
    {
      "id": "p1-1",
      "level": "P1",
      "xy": [
        215,
        348
      ]
    },
    {
      "id": "p1-2",
      "level": "P1",
      "xy": [
        632,
        358
      ]
    },
    {
      "id": "p1-3",
      "level": "P1",
      "xy": [
        213,
        440
      ]
    },
    {
      "id": "p1-4",
      "level": "P1",
      "xy": [
        318,
        452
      ]
    },
    {
      "id": "p1-5",
      "level": "P1",
      "xy": [
        610,
        455
      ]
    },
    {
      "id": "p1-6",
      "level": "P1",
      "xy": [
        640,
        440
      ]
    },
    {
      "id": "p1-7",
      "level": "P1",
      "xy": [
        765,
        225
      ]
    },
    {
      "id": "p1-8",
      "level": "P1",
      "xy": [
        638,
        300
      ]
    },
    {
      "id": "p1-9",
      "level": "P1",
      "xy": [
        642,
        390
      ]
    },
    {
      "id": "p1-10",
      "level": "P1",
      "xy": [
        640,
        555
      ]
    },
    {
      "id": "p1-11",
      "level": "P1",
      "xy": [
        640,
        680
      ]
    },
    {
      "id": "p1-12",
      "level": "P1",
      "xy": [
        937,
        382
      ]
    },
    {
      "id": "p1-13",
      "level": "P1",
      "xy": [
        943,
        340
      ]
    },
    {
      "id": "p1-14",
      "level": "P1",
      "xy": [
        942,
        545
      ]
    },
    {
      "id": "p1-15",
      "level": "P1",
      "xy": [
        905,
        560
      ]
    },
    {
      "id": "p1-16",
      "level": "P1",
      "xy": [
        822,
        205
      ]
    },
    {
      "id": "p1-17",
      "level": "P1",
      "xy": [
        943,
        190
      ]
    },
    {
      "id": "p1-18",
      "level": "P1",
      "xy": [
        700,
        668
      ]
    },
    {
      "id": "p1-19",
      "level": "P1",
      "xy": [
        915,
        665
      ]
    },
    {
      "id": "p2-46",
      "level": "P2",
      "xy": [
        283.7,
        95
      ]
    },
    {
      "id": "p2-48",
      "level": "P2",
      "xy": [
        656,
        200.8
      ]
    },
    {
      "id": "p2-50",
      "level": "P2",
      "xy": [
        839.9,
        172.8
      ]
    },
    {
      "id": "p2-52",
      "level": "P2",
      "xy": [
        226,
        338.7
      ]
    },
    {
      "id": "p2-54",
      "level": "P2",
      "xy": [
        848.4,
        503.9
      ]
    },
    {
      "id": "p2-56",
      "level": "P2",
      "xy": [
        704.5,
        854.5
      ]
    },
    {
      "id": "p2-58",
      "level": "P2",
      "xy": [
        854,
        848
      ]
    },
    {
      "id": "p2-60",
      "level": "P2",
      "xy": [
        680,
        1256.3
      ]
    },
    {
      "id": "p2-62",
      "level": "P2",
      "xy": [
        630.7,
        671.3
      ]
    },
    {
      "id": "p1-21",
      "level": "P1",
      "xy": [
        396.8,
        352.4
      ]
    },
    {
      "id": "p2-64",
      "level": "P2",
      "xy": [
        680,
        1178
      ]
    }
  ],
  "edges": [
    {
      "id": "e-1",
      "from": "p2-1",
      "to": "p2-2",
      "mode": [
        "car",
        "foot"
      ],
      "len": 13.5,
      "instruction": null
    },
    {
      "id": "e-2",
      "from": "p2-2",
      "to": "p2-3",
      "mode": [
        "car",
        "foot"
      ],
      "len": 3.3,
      "instruction": null
    },
    {
      "id": "e-4",
      "from": "p2-4",
      "to": "p2-5",
      "mode": [
        "car",
        "foot"
      ],
      "len": 39.3,
      "instruction": null
    },
    {
      "id": "e-5",
      "from": "p2-6",
      "to": "p2-7",
      "mode": [
        "car",
        "foot"
      ],
      "len": 34.2,
      "instruction": null
    },
    {
      "id": "e-6",
      "from": "p2-6",
      "to": "p2-5",
      "mode": [
        "car",
        "foot"
      ],
      "len": 4.6,
      "instruction": null
    },
    {
      "id": "e-8",
      "from": "p2-8",
      "to": "p2-9",
      "mode": [
        "car",
        "foot"
      ],
      "len": 8.8,
      "instruction": null
    },
    {
      "id": "e-9",
      "from": "p2-9",
      "to": "p2-10",
      "mode": [
        "car",
        "foot"
      ],
      "len": 14.3,
      "instruction": null
    },
    {
      "id": "e-11",
      "from": "p2-4",
      "to": "p2-12",
      "mode": [
        "car",
        "foot"
      ],
      "len": 32.2,
      "instruction": null
    },
    {
      "id": "e-12",
      "from": "p2-12",
      "to": "p2-13",
      "mode": [
        "car",
        "foot"
      ],
      "len": 13.7,
      "instruction": null
    },
    {
      "id": "e-13",
      "from": "p2-1",
      "to": "p2-14",
      "mode": [
        "car",
        "foot"
      ],
      "len": 16.5,
      "instruction": null
    },
    {
      "id": "e-14",
      "from": "p2-14",
      "to": "p2-15",
      "mode": [
        "car",
        "foot"
      ],
      "len": 17.9,
      "instruction": null
    },
    {
      "id": "e-15",
      "from": "p2-14",
      "to": "p2-12",
      "mode": [
        "car",
        "foot"
      ],
      "len": 53.2,
      "instruction": null
    },
    {
      "id": "e-17",
      "from": "p2-16",
      "to": "p2-13",
      "mode": [
        "car",
        "foot"
      ],
      "len": 16.2,
      "instruction": null
    },
    {
      "id": "e-18",
      "from": "p2-13",
      "to": "p2-10",
      "mode": [
        "car",
        "foot"
      ],
      "len": 43.1,
      "instruction": null
    },
    {
      "id": "e-19",
      "from": "p2-10",
      "to": "p2-11",
      "mode": [
        "car",
        "foot"
      ],
      "len": 31.7,
      "instruction": null
    },
    {
      "id": "e-22",
      "from": "p2-16",
      "to": "p2-19",
      "mode": [
        "car",
        "foot"
      ],
      "len": 36.5,
      "instruction": null
    },
    {
      "id": "e-23",
      "from": "p2-19",
      "to": "p2-20",
      "mode": [
        "car",
        "foot"
      ],
      "len": 4.3,
      "instruction": null
    },
    {
      "id": "e-24",
      "from": "p2-15",
      "to": "p2-21",
      "mode": [
        "car",
        "foot"
      ],
      "len": 5.9,
      "instruction": null
    },
    {
      "id": "e-25",
      "from": "p2-21",
      "to": "p2-22",
      "mode": [
        "car",
        "foot"
      ],
      "len": 29.8,
      "instruction": null
    },
    {
      "id": "e-26",
      "from": "p2-22",
      "to": "p2-23",
      "mode": [
        "car",
        "foot"
      ],
      "len": 5.3,
      "instruction": null
    },
    {
      "id": "e-27",
      "from": "p2-23",
      "to": "p2-20",
      "mode": [
        "car",
        "foot"
      ],
      "len": 53.6,
      "instruction": null
    },
    {
      "id": "e-28",
      "from": "p2-20",
      "to": "p2-24",
      "mode": [
        "car",
        "foot"
      ],
      "len": 14.6,
      "instruction": null
    },
    {
      "id": "e-29",
      "from": "p2-24",
      "to": "p2-25",
      "mode": [
        "car",
        "foot"
      ],
      "len": 41,
      "instruction": null
    },
    {
      "id": "e-30",
      "from": "p2-13",
      "to": "p2-26",
      "mode": [
        "car",
        "foot"
      ],
      "len": 16.7,
      "instruction": null
    },
    {
      "id": "e-31",
      "from": "p2-26",
      "to": "p2-24",
      "mode": [
        "car",
        "foot"
      ],
      "len": 22.4,
      "instruction": null
    },
    {
      "id": "e-32",
      "from": "p2-24",
      "to": "p2-27",
      "mode": [
        "car",
        "foot"
      ],
      "len": 24.2,
      "instruction": null
    },
    {
      "id": "e-33",
      "from": "p2-26",
      "to": "p2-28",
      "mode": [
        "car",
        "foot"
      ],
      "len": 40.9,
      "instruction": null
    },
    {
      "id": "e-34",
      "from": "p2-10",
      "to": "p2-28",
      "mode": [
        "car",
        "foot"
      ],
      "len": 15.4,
      "instruction": null
    },
    {
      "id": "e-35",
      "from": "p2-28",
      "to": "p2-25",
      "mode": [
        "car",
        "foot"
      ],
      "len": 22.4,
      "instruction": null
    },
    {
      "id": "e-36",
      "from": "p2-25",
      "to": "p2-29",
      "mode": [
        "car",
        "foot"
      ],
      "len": 29.3,
      "instruction": null
    },
    {
      "id": "e-38",
      "from": "p2-27",
      "to": "p2-31",
      "mode": [
        "car",
        "foot"
      ],
      "len": 12.3,
      "instruction": null
    },
    {
      "id": "e-39",
      "from": "p2-31",
      "to": "p2-32",
      "mode": [
        "car",
        "foot"
      ],
      "len": 16,
      "instruction": null
    },
    {
      "id": "e-41",
      "from": "p2-29",
      "to": "p2-17",
      "mode": [
        "car",
        "foot"
      ],
      "len": 29.1,
      "instruction": null
    },
    {
      "id": "e-42",
      "from": "p2-31",
      "to": "p2-33",
      "mode": [
        "car",
        "foot"
      ],
      "len": 33.9,
      "instruction": null
    },
    {
      "id": "e-43",
      "from": "p2-33",
      "to": "p2-34",
      "mode": [
        "car",
        "foot"
      ],
      "len": 15.9,
      "instruction": null
    },
    {
      "id": "e-44",
      "from": "p2-34",
      "to": "p2-35",
      "mode": [
        "car",
        "foot"
      ],
      "len": 9.4,
      "instruction": null
    },
    {
      "id": "e-45",
      "from": "p2-35",
      "to": "p2-36",
      "mode": [
        "car",
        "foot"
      ],
      "len": 11.5,
      "instruction": null
    },
    {
      "id": "e-46",
      "from": "p2-36",
      "to": "p2-30",
      "mode": [
        "car",
        "foot"
      ],
      "len": 5.5,
      "instruction": null
    },
    {
      "id": "e-47",
      "from": "p2-30",
      "to": "p2-37",
      "mode": [
        "car",
        "foot"
      ],
      "len": 10.7,
      "instruction": null
    },
    {
      "id": "e-48",
      "from": "p2-37",
      "to": "p2-18",
      "mode": [
        "car",
        "foot"
      ],
      "len": 17.5,
      "instruction": null
    },
    {
      "id": "e-49",
      "from": "p2-18",
      "to": "p2-38",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6.8,
      "instruction": null
    },
    {
      "id": "e-52",
      "from": "p2-37",
      "to": "p2-41",
      "mode": [
        "car",
        "foot"
      ],
      "len": 43.5,
      "instruction": null
    },
    {
      "id": "e-53",
      "from": "p2-41",
      "to": "p2-42",
      "mode": [
        "car",
        "foot"
      ],
      "len": 17.1,
      "instruction": null
    },
    {
      "id": "e-54",
      "from": "p2-42",
      "to": "p2-43",
      "mode": [
        "car",
        "foot"
      ],
      "len": 5.5,
      "instruction": null
    },
    {
      "id": "e-55",
      "from": "p2-43",
      "to": "p2-44",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6.5,
      "instruction": null
    },
    {
      "id": "e-56",
      "from": "p2-39",
      "to": "p2-41",
      "mode": [
        "car",
        "foot"
      ],
      "len": 16.1,
      "instruction": null
    },
    {
      "id": "e-57",
      "from": "p2-40",
      "to": "p2-44",
      "mode": [
        "car",
        "foot"
      ],
      "len": 22.6,
      "instruction": null
    },
    {
      "id": "e-59",
      "from": "p1-1",
      "to": "p1-3",
      "mode": [
        "car",
        "foot"
      ],
      "len": 14.6,
      "instruction": null
    },
    {
      "id": "e-60",
      "from": "p1-3",
      "to": "p1-4",
      "mode": [
        "car",
        "foot"
      ],
      "len": 16.8,
      "instruction": null
    },
    {
      "id": "e-61",
      "from": "p1-4",
      "to": "p1-5",
      "mode": [
        "car",
        "foot"
      ],
      "len": 46.4,
      "instruction": null
    },
    {
      "id": "e-62",
      "from": "p1-5",
      "to": "p1-6",
      "mode": [
        "car",
        "foot"
      ],
      "len": 5.3,
      "instruction": null
    },
    {
      "id": "e-63",
      "from": "p1-7",
      "to": "p1-8",
      "mode": [
        "car",
        "foot"
      ],
      "len": 23.5,
      "instruction": null
    },
    {
      "id": "e-64",
      "from": "p1-8",
      "to": "p1-2",
      "mode": [
        "car",
        "foot"
      ],
      "len": 9.3,
      "instruction": null
    },
    {
      "id": "e-65",
      "from": "p1-2",
      "to": "p1-9",
      "mode": [
        "car",
        "foot"
      ],
      "len": 5.3,
      "instruction": null
    },
    {
      "id": "e-66",
      "from": "p1-9",
      "to": "p1-6",
      "mode": [
        "car",
        "foot"
      ],
      "len": 8,
      "instruction": null
    },
    {
      "id": "e-67",
      "from": "p1-6",
      "to": "p1-10",
      "mode": [
        "car",
        "foot"
      ],
      "len": 18.3,
      "instruction": null
    },
    {
      "id": "e-68",
      "from": "p1-10",
      "to": "p1-11",
      "mode": [
        "car",
        "foot"
      ],
      "len": 19.9,
      "instruction": null
    },
    {
      "id": "e-69",
      "from": "p1-9",
      "to": "p1-12",
      "mode": [
        "car",
        "foot"
      ],
      "len": 46.9,
      "instruction": null
    },
    {
      "id": "e-70",
      "from": "p1-12",
      "to": "p1-13",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6.7,
      "instruction": null
    },
    {
      "id": "e-71",
      "from": "p1-12",
      "to": "p1-14",
      "mode": [
        "car",
        "foot"
      ],
      "len": 25.9,
      "instruction": null
    },
    {
      "id": "e-72",
      "from": "p1-14",
      "to": "p1-15",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6.3,
      "instruction": null
    },
    {
      "id": "e-73",
      "from": "p1-15",
      "to": "p1-10",
      "mode": [
        "car",
        "foot"
      ],
      "len": 42.1,
      "instruction": null
    },
    {
      "id": "e-74",
      "from": "p1-7",
      "to": "p1-16",
      "mode": [
        "car",
        "foot"
      ],
      "len": 9.6,
      "instruction": null
    },
    {
      "id": "e-75",
      "from": "p1-16",
      "to": "p1-17",
      "mode": [
        "car",
        "foot"
      ],
      "len": 19.4,
      "instruction": null
    },
    {
      "id": "e-76",
      "from": "p1-11",
      "to": "p1-18",
      "mode": [
        "car",
        "foot"
      ],
      "len": 9.7,
      "instruction": null
    },
    {
      "id": "e-77",
      "from": "p1-18",
      "to": "p1-19",
      "mode": [
        "car",
        "foot"
      ],
      "len": 34.2,
      "instruction": null
    },
    {
      "id": "e-78",
      "from": "p2-3",
      "to": "p2-46",
      "mode": [
        "car",
        "foot"
      ],
      "len": 20.7,
      "instruction": null
    },
    {
      "id": "e-79",
      "from": "p2-46",
      "to": "p2-4",
      "mode": [
        "car",
        "foot"
      ],
      "len": 31.4,
      "instruction": null
    },
    {
      "id": "e-80",
      "from": "p2-46",
      "to": "lift-e",
      "mode": [
        "car",
        "foot"
      ],
      "len": 9.3,
      "instruction": "Block E lift and stairs are off the aisle here.",
      "instructionRev": "Come out of the Block E lift lobby into the aisle."
    },
    {
      "id": "e-81",
      "from": "p2-5",
      "to": "p2-48",
      "mode": [
        "car",
        "foot"
      ],
      "len": 21.1,
      "instruction": null
    },
    {
      "id": "e-82",
      "from": "p2-48",
      "to": "p2-8",
      "mode": [
        "car",
        "foot"
      ],
      "len": 3.6,
      "instruction": null
    },
    {
      "id": "e-83",
      "from": "p2-48",
      "to": "lift-d",
      "mode": [
        "car",
        "foot"
      ],
      "len": 19.5,
      "instruction": "Block D lift and stairs are off the aisle here.",
      "instructionRev": "Come out of the Block D lift lobby into the aisle."
    },
    {
      "id": "e-84",
      "from": "p2-7",
      "to": "p2-50",
      "mode": [
        "car",
        "foot"
      ],
      "len": 20.3,
      "instruction": null
    },
    {
      "id": "e-85",
      "from": "p2-50",
      "to": "p2-11",
      "mode": [
        "car",
        "foot"
      ],
      "len": 31.8,
      "instruction": null
    },
    {
      "id": "e-86",
      "from": "p2-50",
      "to": "lift-c",
      "mode": [
        "car",
        "foot"
      ],
      "len": 7.2,
      "instruction": "Block C lift and stairs are off the aisle here.",
      "instructionRev": "Come out of the Block C lift lobby into the aisle."
    },
    {
      "id": "e-87",
      "from": "p2-15",
      "to": "p2-52",
      "mode": [
        "car",
        "foot"
      ],
      "len": 22.6,
      "instruction": null
    },
    {
      "id": "e-88",
      "from": "p2-52",
      "to": "p2-16",
      "mode": [
        "car",
        "foot"
      ],
      "len": 26.8,
      "instruction": null
    },
    {
      "id": "e-89",
      "from": "p2-52",
      "to": "lift-f",
      "mode": [
        "car",
        "foot"
      ],
      "len": 8.7,
      "instruction": "Block F lift and stairs are off the aisle here.",
      "instructionRev": "Come out of the Block F lift lobby into the aisle."
    },
    {
      "id": "e-90",
      "from": "p2-11",
      "to": "p2-54",
      "mode": [
        "car",
        "foot"
      ],
      "len": 31.1,
      "instruction": null
    },
    {
      "id": "e-91",
      "from": "p2-54",
      "to": "p2-17",
      "mode": [
        "car",
        "foot"
      ],
      "len": 33.8,
      "instruction": null
    },
    {
      "id": "e-92",
      "from": "p2-54",
      "to": "lift-b",
      "mode": [
        "car",
        "foot"
      ],
      "len": 13.9,
      "instruction": "Block B lift and stairs are off the aisle here.",
      "instructionRev": "Come out of the Block B lift lobby into the aisle."
    },
    {
      "id": "e-93",
      "from": "p2-29",
      "to": "p2-56",
      "mode": [
        "car",
        "foot"
      ],
      "len": 31.5,
      "instruction": null
    },
    {
      "id": "e-94",
      "from": "p2-56",
      "to": "p2-30",
      "mode": [
        "car",
        "foot"
      ],
      "len": 21.6,
      "instruction": null
    },
    {
      "id": "e-95",
      "from": "p2-56",
      "to": "lift-a",
      "mode": [
        "car",
        "foot"
      ],
      "len": 7.9,
      "instruction": "Block A lift and stairs are off the aisle here.",
      "instructionRev": "Come out of the Block A lift lobby into the aisle."
    },
    {
      "id": "e-96",
      "from": "p2-17",
      "to": "p2-58",
      "mode": [
        "car",
        "foot"
      ],
      "len": 31.5,
      "instruction": null
    },
    {
      "id": "e-97",
      "from": "p2-58",
      "to": "p2-18",
      "mode": [
        "car",
        "foot"
      ],
      "len": 20.7,
      "instruction": null
    },
    {
      "id": "e-98",
      "from": "p2-58",
      "to": "lift-a2",
      "mode": [
        "car",
        "foot"
      ],
      "len": 12.1,
      "instruction": "The second Block A lift and stairs are off the aisle here.",
      "instructionRev": "Come out of the Block A lift lobby into the aisle."
    },
    {
      "id": "e-99",
      "from": "p2-39",
      "to": "p2-60",
      "mode": [
        "car",
        "foot"
      ],
      "len": 10.7,
      "instruction": null
    },
    {
      "id": "e-100",
      "from": "p2-60",
      "to": "p2-40",
      "mode": [
        "car",
        "foot"
      ],
      "len": 15,
      "instruction": null
    },
    {
      "id": "e-101",
      "from": "p2-60",
      "to": "visitor",
      "mode": [
        "car",
        "foot"
      ],
      "len": 3.4,
      "instruction": "Visitor parking: the bays marked VP along this aisle.",
      "instructionRev": "Come out of the visitor bays into the aisle."
    },
    {
      "id": "e-102",
      "from": "p2-32",
      "to": "p2-62",
      "mode": [
        "car",
        "foot"
      ],
      "len": 1.7,
      "instruction": null
    },
    {
      "id": "e-103",
      "from": "p2-29",
      "to": "p2-62",
      "mode": [
        "car",
        "foot"
      ],
      "len": 13.2,
      "instruction": null,
      "oneway": true
    },
    {
      "id": "e-104",
      "from": "p2-62",
      "to": "main-ramp-foot",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6,
      "instruction": "Turn towards the foot of the entry ramp.",
      "instructionRev": "At the foot of the ramp, cross the speed breaker and turn left under the sign '← B, C, D, E, F, A'.",
      "photo": "main-ramp-foot-left-b1"
    },
    {
      "id": "e-105",
      "from": "p1-1",
      "to": "p1-21",
      "mode": [
        "car",
        "foot"
      ],
      "len": 28.9,
      "instruction": null
    },
    {
      "id": "e-106",
      "from": "p1-21",
      "to": "p1-2",
      "mode": [
        "car",
        "foot"
      ],
      "len": 37.4,
      "instruction": null
    },
    {
      "id": "e-107",
      "from": "p1-21",
      "to": "a-ramp-foot",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6,
      "instruction": "Turn towards the foot of the Block A ramp.",
      "instructionRev": "At the foot of the ramp, cross the steel grating and turn sharp left round the end of the wall.",
      "photo": "ablock-b1-ramp-foot-left"
    },
    {
      "id": "e-108",
      "from": "p1-8",
      "to": "a2-ramp-top",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6,
      "instruction": "In the open area by the end wall, sweep sharp left onto the down ramp.",
      "instructionRev": "Come off the ramp into Block A's B1."
    },
    {
      "id": "e-109",
      "from": "p2-36",
      "to": "p2-64",
      "mode": [
        "car",
        "foot"
      ],
      "len": 39.3,
      "instruction": null
    },
    {
      "id": "e-110",
      "from": "p2-64",
      "to": "p2-39",
      "mode": [
        "car",
        "foot"
      ],
      "len": 4.2,
      "instruction": null
    },
    {
      "id": "e-111",
      "from": "p2-64",
      "to": "a2-ramp-foot",
      "mode": [
        "car",
        "foot"
      ],
      "len": 6,
      "instruction": "Turn towards the ramp up to Block A's B1.",
      "instructionRev": "At the foot of the ramp, with a blank wall ahead, turn left round the end of the ramp wall into the hall.",
      "photo": "ablock-b2-ramp-foot-left"
    },
    {
      "id": "e-112",
      "from": "gate",
      "to": "g-forecourt",
      "mode": [
        "car",
        "foot"
      ],
      "len": 30,
      "instruction": "Come in through the main gate and follow the paver driveway towards Block A.",
      "instructionRev": "Follow the paver driveway back to the main gate."
    },
    {
      "id": "e-113",
      "from": "g-forecourt",
      "to": "g-apron",
      "mode": [
        "car",
        "foot"
      ],
      "len": 25,
      "instruction": "At Block A's forecourt keep left round the planter, then drive along the front of Block A with the hedge on your left until the pavers end.",
      "instructionRev": "Drive back along the front of Block A to the forecourt.",
      "photo": "ablock-block-a-forecourt-left"
    },
    {
      "id": "e-114",
      "from": "g-apron",
      "to": "g-bend",
      "mode": [
        "car",
        "foot"
      ],
      "len": 25,
      "instruction": "On the concrete apron, turn right at the clubhouse garden wall and go over the speed breaker.",
      "instructionRev": "Follow the road back to the concrete apron by Block A.",
      "photo": "main-apron-right-turn"
    },
    {
      "id": "e-115",
      "from": "g-bend",
      "to": "g-guard",
      "mode": [
        "car",
        "foot"
      ],
      "len": 45,
      "instruction": "Follow the road round the long right-hand bend, over the second speed breaker, to the guard at the red barricades.",
      "instructionRev": "Follow the road back round the bend towards Block A."
    },
    {
      "id": "e-116",
      "from": "g-guard",
      "to": "g-main-ramp",
      "mode": [
        "car",
        "foot"
      ],
      "len": 10,
      "instruction": "At the guard, turn right under the 7.2 ft clearance bar: BASEMENT ENTRY FOR A, B, C, D, E, F.",
      "instructionRev": "Come off the ramp and turn left past the guard.",
      "photo": "main-guard-right-under-bar"
    },
    {
      "id": "e-117",
      "from": "g-apron",
      "to": "g-a-ramp",
      "mode": [
        "car",
        "foot"
      ],
      "len": 15,
      "instruction": "On the concrete apron, turn sharp left towards the CLUBHOUSE ENTRANCE / GUEST PARKING sign and the steel pergola.",
      "instructionRev": "Come off the Block A ramp onto the concrete apron.",
      "photo": "ablock-apron-guest-parking-left"
    },
    {
      "id": "e-118",
      "from": "g-main-ramp",
      "to": "main-ramp-foot",
      "mode": [
        "car",
        "foot"
      ],
      "len": 22,
      "instruction": "Drive straight down the covered ramp into Basement 1.",
      "instructionRev": "Drive up the entry ramp to the ground."
    },
    {
      "id": "e-119",
      "from": "g-a-ramp",
      "to": "a-ramp-foot",
      "mode": [
        "car",
        "foot"
      ],
      "len": 20,
      "instruction": "Drive straight down the covered ramp under the pergola into Block A's B1 (7.2 ft clearance).",
      "instructionRev": "Drive up the Block A ramp to the ground."
    },
    {
      "id": "e-120",
      "from": "a2-ramp-top",
      "to": "a2-ramp-foot",
      "mode": [
        "car",
        "foot"
      ],
      "len": 22,
      "instruction": "Drive straight down the ramp to Basement 1 (A Block B2).",
      "instructionRev": "Drive up the ramp to Block A's B1."
    }
  ],
  "slots": [
    {
      "id": "s-1",
      "edge": "e-56",
      "t": 0.518,
      "side": -1,
      "flat": "A-1108",
      "src": "bay:B1#13/0",
      "at": [
        724,
        1165.3
      ]
    },
    {
      "id": "s-2",
      "edge": "e-52",
      "t": 0.408,
      "side": -1,
      "flat": "A-1102",
      "src": "bay:B1#17/0",
      "at": [
        789.4,
        1064.5
      ]
    },
    {
      "id": "s-3",
      "edge": "e-52",
      "t": 0.709,
      "side": 1,
      "flat": "A-501",
      "src": "bay:B1#19/0",
      "at": [
        739.5,
        1133.4
      ]
    },
    {
      "id": "s-4",
      "edge": "e-52",
      "t": 0.588,
      "side": 1,
      "flat": "A-1203",
      "src": "bay:B1#20/0",
      "at": [
        740.8,
        1105.6
      ]
    },
    {
      "id": "s-5",
      "edge": "e-109",
      "t": 0.806,
      "side": -1,
      "flat": "A-406",
      "src": "bay:B1#21/0",
      "at": [
        707.6,
        1137.9
      ]
    },
    {
      "id": "s-6",
      "edge": "e-109",
      "t": 0.642,
      "side": -1,
      "flat": "A-503",
      "src": "bay:B1#22/0",
      "at": [
        705.4,
        1103.8
      ]
    },
    {
      "id": "s-7",
      "edge": "e-109",
      "t": 0.427,
      "side": 1,
      "flat": "A-G3",
      "src": "bay:B1#23/0",
      "at": [
        660.4,
        1059.4
      ]
    },
    {
      "id": "s-8",
      "edge": "e-52",
      "t": 0.277,
      "side": -1,
      "flat": "A-401",
      "src": "bay:B1#24/0",
      "at": [
        789.8,
        1034.4
      ]
    },
    {
      "id": "s-9",
      "edge": "e-52",
      "t": 0.263,
      "side": 1,
      "flat": "A-305",
      "src": "bay:B1#25/0",
      "at": [
        735.5,
        1031.3
      ]
    },
    {
      "id": "s-10",
      "edge": "e-52",
      "t": 0.412,
      "side": 1,
      "flat": "A-1005",
      "src": "bay:B1#26/0",
      "at": [
        737.2,
        1065.4
      ]
    },
    {
      "id": "s-11",
      "edge": "e-109",
      "t": 0.467,
      "side": -1,
      "flat": "A-1306",
      "src": "bay:B1#27/0",
      "at": [
        706.8,
        1067.6
      ]
    },
    {
      "id": "s-12",
      "edge": "e-109",
      "t": 0.281,
      "side": -1,
      "flat": "A-307",
      "src": "bay:B1#28/0",
      "at": [
        708.5,
        1029.1
      ]
    },
    {
      "id": "s-13",
      "edge": "e-109",
      "t": 0.283,
      "side": 1,
      "flat": "A-106",
      "src": "bay:B1#29/0",
      "at": [
        659.2,
        1029.6
      ]
    },
    {
      "id": "s-14",
      "edge": "e-49",
      "t": 1,
      "side": 1,
      "flat": "A-1503",
      "src": "bay:B1#30/0",
      "at": [
        889.4,
        985.3
      ]
    },
    {
      "id": "s-15",
      "edge": "e-49",
      "t": 0.168,
      "side": 1,
      "flat": "A-1104",
      "src": "bay:B1#31/0",
      "at": [
        855.5,
        986.3
      ]
    },
    {
      "id": "s-16",
      "edge": "e-48",
      "t": 0.561,
      "side": 1,
      "flat": "A-1402",
      "src": "bay:B1#32/0",
      "at": [
        820.6,
        992.5
      ]
    },
    {
      "id": "s-17",
      "edge": "e-48",
      "t": 0.325,
      "side": -1,
      "flat": "B-1403",
      "src": "bay:B1#33/0",
      "at": [
        790.8,
        942.2
      ]
    },
    {
      "id": "s-18",
      "edge": "e-48",
      "t": 0.101,
      "side": -1,
      "flat": "A-507",
      "src": "bay:B1#34/0",
      "at": [
        769.2,
        937
      ]
    },
    {
      "id": "s-19",
      "edge": "e-47",
      "t": 0.654,
      "side": -1,
      "flat": "A-401",
      "src": "bay:B1#35/0",
      "at": [
        747.2,
        940.1
      ]
    },
    {
      "id": "s-20",
      "edge": "e-94",
      "t": 0.662,
      "side": -1,
      "flat": "A-303",
      "src": "bay:B1#36/0",
      "at": [
        729.2,
        928.8
      ]
    },
    {
      "id": "s-21",
      "edge": "e-47",
      "t": 0.24,
      "side": 1,
      "flat": "A-605",
      "src": "bay:B1#37/0",
      "at": [
        721.5,
        986.3
      ]
    },
    {
      "id": "s-22",
      "edge": "e-45",
      "t": 0.702,
      "side": -1,
      "flat": "A-1205",
      "src": "bay:B1#38/0",
      "at": [
        666,
        935.5
      ]
    },
    {
      "id": "s-23",
      "edge": "e-45",
      "t": 0.084,
      "side": 1,
      "flat": "A-1505",
      "src": "bay:B1#39/0",
      "at": [
        621.4,
        995.6
      ]
    },
    {
      "id": "s-24",
      "edge": "e-43",
      "t": 0.955,
      "side": -1,
      "flat": "A-205",
      "src": "bay:B1#40/0",
      "at": [
        610.9,
        904.9
      ]
    },
    {
      "id": "s-25",
      "edge": "e-97",
      "t": 0.394,
      "side": -1,
      "flat": "A-1402",
      "src": "bay:B1#41/0",
      "at": [
        917.2,
        889.8
      ]
    },
    {
      "id": "s-26",
      "edge": "e-97",
      "t": 0.712,
      "side": -1,
      "flat": "A-302",
      "src": "bay:B1#42/0",
      "at": [
        877.1,
        925.2
      ]
    },
    {
      "id": "s-27",
      "edge": "e-97",
      "t": 0.723,
      "side": 1,
      "flat": "A-604",
      "src": "bay:B1#43/0",
      "at": [
        825.8,
        927.3
      ]
    },
    {
      "id": "s-28",
      "edge": "e-97",
      "t": 0.356,
      "side": 1,
      "flat": "A-1402",
      "src": "bay:B1#44/0",
      "at": [
        827.3,
        887.3
      ]
    },
    {
      "id": "s-29",
      "edge": "e-94",
      "t": 0.241,
      "side": -1,
      "flat": "A-1002",
      "src": "bay:B1#45/0",
      "at": [
        708.5,
        881.7
      ]
    },
    {
      "id": "s-30",
      "edge": "e-43",
      "t": 0.401,
      "side": -1,
      "flat": "A-1107",
      "src": "bay:B1#46/0",
      "at": [
        583.5,
        867.3
      ]
    },
    {
      "id": "s-31",
      "edge": "e-42",
      "t": 0.885,
      "side": 1,
      "flat": "A-705",
      "src": "bay:B1#47/0",
      "at": [
        517.3,
        835.7
      ]
    },
    {
      "id": "s-32",
      "edge": "e-96",
      "t": 0.834,
      "side": -1,
      "flat": "A-1103",
      "src": "bay:B1#48/0",
      "at": [
        878.7,
        820
      ]
    },
    {
      "id": "s-33",
      "edge": "e-97",
      "t": 0.085,
      "side": 1,
      "flat": "A-506",
      "src": "bay:B1#49/0",
      "at": [
        840.7,
        857.5
      ]
    },
    {
      "id": "s-34",
      "edge": "e-96",
      "t": 0.821,
      "side": 1,
      "flat": "A-1101",
      "src": "bay:B1#50/0",
      "at": [
        837.1,
        818.5
      ]
    },
    {
      "id": "s-35",
      "edge": "e-93",
      "t": 0.677,
      "side": -1,
      "flat": "A-204",
      "src": "bay:B1#51/0",
      "at": [
        703.7,
        801
      ]
    },
    {
      "id": "s-36",
      "edge": "e-93",
      "t": 0.892,
      "side": 1,
      "flat": "A-505",
      "src": "bay:B1#52/0",
      "at": [
        699.6,
        836.8
      ]
    },
    {
      "id": "s-37",
      "edge": "e-42",
      "t": 0.698,
      "side": -1,
      "flat": "A-G6",
      "src": "bay:B1#53/0",
      "at": [
        604.6,
        798.6
      ]
    },
    {
      "id": "s-38",
      "edge": "e-42",
      "t": 0.881,
      "side": -1,
      "flat": "A-808",
      "src": "bay:B1#54/0",
      "at": [
        568,
        832.7
      ]
    },
    {
      "id": "s-39",
      "edge": "e-42",
      "t": 0.787,
      "side": -1,
      "flat": "A-1008",
      "src": "bay:B1#55/0",
      "at": [
        570.4,
        816
      ]
    },
    {
      "id": "s-40",
      "edge": "e-42",
      "t": 0.546,
      "side": 1,
      "flat": "A-G1",
      "src": "bay:B1#56/0",
      "at": [
        511.3,
        775.5
      ]
    },
    {
      "id": "s-41",
      "edge": "e-42",
      "t": 0.711,
      "side": 1,
      "flat": "A-506",
      "src": "bay:B1#57/0",
      "at": [
        520.2,
        804.7
      ]
    },
    {
      "id": "s-42",
      "edge": "e-96",
      "t": 0.586,
      "side": -1,
      "flat": "A-502",
      "src": "bay:B1#58/0",
      "at": [
        877.7,
        778.9
      ]
    },
    {
      "id": "s-43",
      "edge": "e-96",
      "t": 0.289,
      "side": -1,
      "flat": "B-202",
      "src": "bay:B1#59/0",
      "at": [
        875.1,
        729.6
      ]
    },
    {
      "id": "s-44",
      "edge": "e-96",
      "t": 0.394,
      "side": 1,
      "flat": "B-205",
      "src": "bay:B1#60/0",
      "at": [
        848.6,
        747.4
      ]
    },
    {
      "id": "s-45",
      "edge": "e-96",
      "t": 0.535,
      "side": 1,
      "flat": "B-902",
      "src": "bay:B1#61/0",
      "at": [
        837.9,
        771
      ]
    },
    {
      "id": "s-46",
      "edge": "e-93",
      "t": 0.605,
      "side": -1,
      "flat": "A-1204",
      "src": "bay:B1#62/0",
      "at": [
        756.9,
        786.9
      ]
    },
    {
      "id": "s-47",
      "edge": "e-93",
      "t": 0.244,
      "side": -1,
      "flat": "B-902",
      "src": "bay:B1#63/0",
      "at": [
        705,
        729.1
      ]
    },
    {
      "id": "s-48",
      "edge": "e-93",
      "t": 0.381,
      "side": 1,
      "flat": "A-206",
      "src": "bay:B1#64/0",
      "at": [
        697.1,
        752.2
      ]
    },
    {
      "id": "s-49",
      "edge": "e-93",
      "t": 0.569,
      "side": 1,
      "flat": "A-1401",
      "src": "bay:B1#65/0",
      "at": [
        691.3,
        783.7
      ]
    },
    {
      "id": "s-50",
      "edge": "e-103",
      "t": 0.791,
      "side": -1,
      "flat": "A-108",
      "src": "bay:B1#66/0",
      "at": [
        630.6,
        728.8
      ]
    },
    {
      "id": "s-51",
      "edge": "e-42",
      "t": 0.395,
      "side": -1,
      "flat": "B-401",
      "src": "bay:B1#67/0",
      "at": [
        553.6,
        746.7
      ]
    },
    {
      "id": "s-52",
      "edge": "e-42",
      "t": 0.428,
      "side": 1,
      "flat": "A-606",
      "src": "bay:B1#68/0",
      "at": [
        522,
        754
      ]
    },
    {
      "id": "s-53",
      "edge": "e-96",
      "t": 0.042,
      "side": -1,
      "flat": "B-301",
      "src": "bay:B1#69/0",
      "at": [
        907.4,
        688
      ]
    },
    {
      "id": "s-54",
      "edge": "e-96",
      "t": 0.126,
      "side": -1,
      "flat": "B-1201",
      "src": "bay:B1#70/0",
      "at": [
        880.7,
        702.4
      ]
    },
    {
      "id": "s-55",
      "edge": "e-96",
      "t": 0.103,
      "side": -1,
      "flat": "B-405",
      "src": "bay:B1#71/0",
      "at": [
        864.3,
        698.8
      ]
    },
    {
      "id": "s-56",
      "edge": "e-96",
      "t": 0.217,
      "side": 1,
      "flat": "B-502",
      "src": "bay:B1#72/0",
      "at": [
        838.5,
        718.3
      ]
    },
    {
      "id": "s-57",
      "edge": "e-41",
      "t": 0.761,
      "side": -1,
      "flat": "B-1105",
      "src": "bay:B1#73/0",
      "at": [
        814.2,
        677.6
      ]
    },
    {
      "id": "s-58",
      "edge": "e-41",
      "t": 0.339,
      "side": -1,
      "flat": "B-404",
      "src": "bay:B1#74/0",
      "at": [
        749.2,
        673.1
      ]
    },
    {
      "id": "s-59",
      "edge": "e-41",
      "t": 0.107,
      "side": 1,
      "flat": "B-102",
      "src": "bay:B1#75/0",
      "at": [
        714.6,
        692.8
      ]
    },
    {
      "id": "s-60",
      "edge": "e-103",
      "t": 0.732,
      "side": 1,
      "flat": "B-203",
      "src": "bay:B1#76/0",
      "at": [
        651.7,
        664.6
      ]
    },
    {
      "id": "s-61",
      "edge": "e-102",
      "t": 0.543,
      "side": -1,
      "flat": "B-1403",
      "src": "bay:B1#77/0",
      "at": [
        628.5,
        663.7
      ]
    },
    {
      "id": "s-62",
      "edge": "e-39",
      "t": 0.1,
      "side": -1,
      "flat": "B-805",
      "src": "bay:B1#78/0",
      "at": [
        545.4,
        666.5
      ]
    },
    {
      "id": "s-63",
      "edge": "e-38",
      "t": 0.264,
      "side": 1,
      "flat": "A-1408",
      "src": "bay:B1#79/0",
      "at": [
        487.4,
        691.9
      ]
    },
    {
      "id": "s-64",
      "edge": "e-38",
      "t": 0.001,
      "side": 1,
      "flat": "A-105",
      "src": "bay:B1#80/0",
      "at": [
        469.5,
        696.1
      ]
    },
    {
      "id": "s-65",
      "edge": "e-28",
      "t": 0.096,
      "side": 1,
      "flat": "F-602",
      "src": "bay:B1#81/0",
      "at": [
        394.4,
        567
      ]
    },
    {
      "id": "s-66",
      "edge": "e-27",
      "t": 0.783,
      "side": 1,
      "flat": "F-203",
      "src": "bay:B1#82/0",
      "at": [
        325.1,
        565.5
      ]
    },
    {
      "id": "s-67",
      "edge": "e-27",
      "t": 0.71,
      "side": 1,
      "flat": "F-202",
      "src": "bay:B1#83/0",
      "at": [
        304.5,
        567
      ]
    },
    {
      "id": "s-68",
      "edge": "e-91",
      "t": 0.814,
      "side": -1,
      "flat": "B-101",
      "src": "bay:B1#85/0",
      "at": [
        876.1,
        648.5
      ]
    },
    {
      "id": "s-69",
      "edge": "e-96",
      "t": 0.03,
      "side": -1,
      "flat": "B-503",
      "src": "bay:B1#86/0",
      "at": [
        878.7,
        686.5
      ]
    },
    {
      "id": "s-70",
      "edge": "e-91",
      "t": 0.912,
      "side": -1,
      "flat": "B-1101",
      "src": "bay:B1#87/0",
      "at": [
        877.7,
        666
      ]
    },
    {
      "id": "s-71",
      "edge": "e-36",
      "t": 0.797,
      "side": 1,
      "flat": "B-1402",
      "src": "bay:B1#88/0",
      "at": [
        682,
        659.5
      ]
    },
    {
      "id": "s-72",
      "edge": "e-39",
      "t": 1,
      "side": -1,
      "flat": "B-1405",
      "src": "bay:B1#89/0",
      "at": [
        625.1,
        621.9
      ]
    },
    {
      "id": "s-73",
      "edge": "e-39",
      "t": 0.697,
      "side": -1,
      "flat": "B-604",
      "src": "bay:B1#90/0",
      "at": [
        594.5,
        650.1
      ]
    },
    {
      "id": "s-74",
      "edge": "e-39",
      "t": 0.492,
      "side": -1,
      "flat": "B-1404",
      "src": "bay:B1#91/0",
      "at": [
        576.3,
        641.8
      ]
    },
    {
      "id": "s-75",
      "edge": "e-39",
      "t": 0.2,
      "side": -1,
      "flat": "B-1004",
      "src": "bay:B1#92/0",
      "at": [
        550.8,
        633.2
      ]
    },
    {
      "id": "s-76",
      "edge": "e-38",
      "t": 0.776,
      "side": -1,
      "flat": "B-1302",
      "src": "bay:B1#93/0",
      "at": [
        529.7,
        636.3
      ]
    },
    {
      "id": "s-77",
      "edge": "e-32",
      "t": 0.739,
      "side": -1,
      "flat": "B-804",
      "src": "bay:B1#94/0",
      "at": [
        511.5,
        630.7
      ]
    },
    {
      "id": "s-78",
      "edge": "e-32",
      "t": 0.614,
      "side": 1,
      "flat": "A-1108",
      "src": "bay:B1#95/0",
      "at": [
        468.4,
        618.1
      ]
    },
    {
      "id": "s-79",
      "edge": "e-32",
      "t": 0.811,
      "side": 1,
      "flat": "F-203",
      "src": "bay:B1#96/0",
      "at": [
        443.6,
        645.2
      ]
    },
    {
      "id": "s-80",
      "edge": "e-28",
      "t": 0.561,
      "side": 1,
      "flat": "D-101",
      "src": "bay:B1#97/0",
      "at": [
        430.2,
        569.1
      ]
    },
    {
      "id": "s-81",
      "edge": "e-27",
      "t": 0.979,
      "side": 1,
      "flat": "F-804",
      "src": "bay:B1#98/0",
      "at": [
        380,
        576.2
      ]
    },
    {
      "id": "s-82",
      "edge": "e-27",
      "t": 0.84,
      "side": 1,
      "flat": "F-204",
      "src": "bay:B1#99/0",
      "at": [
        341,
        566.5
      ]
    },
    {
      "id": "s-83",
      "edge": "e-27",
      "t": 0.659,
      "side": 1,
      "flat": "F-201",
      "src": "bay:B1#100/0",
      "at": [
        290.1,
        564.4
      ]
    },
    {
      "id": "s-84",
      "edge": "e-27",
      "t": 0.574,
      "side": 1,
      "flat": "F-703",
      "src": "bay:B1#101/0",
      "at": [
        266,
        571.6
      ]
    },
    {
      "id": "s-85",
      "edge": "e-27",
      "t": 0.46,
      "side": 1,
      "flat": "F-501",
      "src": "bay:B1#102/0",
      "at": [
        233.7,
        573.2
      ]
    },
    {
      "id": "s-86",
      "edge": "e-27",
      "t": 0.263,
      "side": 1,
      "flat": "F-505",
      "src": "bay:B1#103/0",
      "at": [
        178.2,
        569.1
      ]
    },
    {
      "id": "s-87",
      "edge": "e-27",
      "t": 0.082,
      "side": 1,
      "flat": "F-704",
      "src": "bay:B1#104/0",
      "at": [
        127.4,
        557.2
      ]
    },
    {
      "id": "s-88",
      "edge": "e-26",
      "t": 1,
      "side": 1,
      "flat": "F-401",
      "src": "bay:B1#105/0",
      "at": [
        86.8,
        555.7
      ]
    },
    {
      "id": "s-89",
      "edge": "e-25",
      "t": 1,
      "side": 1,
      "flat": "F-803",
      "src": "bay:B1#106/0",
      "at": [
        56.5,
        535.2
      ]
    },
    {
      "id": "s-90",
      "edge": "e-25",
      "t": 1,
      "side": 1,
      "flat": "F-801",
      "src": "bay:B1#107/0",
      "at": [
        55,
        518.7
      ]
    },
    {
      "id": "s-91",
      "edge": "e-91",
      "t": 0.733,
      "side": -1,
      "flat": "B-504",
      "src": "bay:B1#108/0",
      "at": [
        879.7,
        634.1
      ]
    },
    {
      "id": "s-92",
      "edge": "e-91",
      "t": 0.661,
      "side": -1,
      "flat": "B-1504",
      "src": "bay:B1#110/0",
      "at": [
        877.1,
        621.3
      ]
    },
    {
      "id": "s-93",
      "edge": "e-36",
      "t": 0.487,
      "side": -1,
      "flat": "B-701",
      "src": "bay:B1#111/0",
      "at": [
        766.2,
        601.4
      ]
    },
    {
      "id": "s-94",
      "edge": "e-36",
      "t": 0.395,
      "side": -1,
      "flat": "B-803",
      "src": "bay:B1#112/0",
      "at": [
        693.5,
        595.7
      ]
    },
    {
      "id": "s-95",
      "edge": "e-36",
      "t": 0.325,
      "side": 1,
      "flat": "B-1305",
      "src": "bay:B1#113/0",
      "at": [
        672.2,
        587.3
      ]
    },
    {
      "id": "s-96",
      "edge": "e-29",
      "t": 0.75,
      "side": 1,
      "flat": "B-803",
      "src": "bay:B1#114/0",
      "at": [
        627,
        588.2
      ]
    },
    {
      "id": "s-97",
      "edge": "e-29",
      "t": 0.674,
      "side": 1,
      "flat": "D-G3",
      "src": "bay:B1#115/0",
      "at": [
        609.5,
        539.7
      ]
    },
    {
      "id": "s-98",
      "edge": "e-29",
      "t": 0.567,
      "side": 1,
      "flat": "B-702",
      "src": "bay:B1#116/0",
      "at": [
        587.2,
        580.1
      ]
    },
    {
      "id": "s-99",
      "edge": "e-29",
      "t": 0.512,
      "side": 1,
      "flat": "D-803",
      "src": "bay:B1#117/0",
      "at": [
        574.6,
        538
      ]
    },
    {
      "id": "s-100",
      "edge": "e-29",
      "t": 0.425,
      "side": -1,
      "flat": "D-202",
      "src": "bay:B1#118/0",
      "at": [
        555.8,
        538.1
      ]
    },
    {
      "id": "s-101",
      "edge": "e-29",
      "t": 0.33,
      "side": -1,
      "flat": "D-G6",
      "src": "bay:B1#119/0",
      "at": [
        535.3,
        538.1
      ]
    },
    {
      "id": "s-102",
      "edge": "e-29",
      "t": 0.243,
      "side": -1,
      "flat": "D-305",
      "src": "bay:B1#120/0",
      "at": [
        516.5,
        538.6
      ]
    },
    {
      "id": "s-103",
      "edge": "e-32",
      "t": 0.272,
      "side": 1,
      "flat": "B-405",
      "src": "bay:B1#121/0",
      "at": [
        466.4,
        574.5
      ]
    },
    {
      "id": "s-104",
      "edge": "e-27",
      "t": 0.924,
      "side": 1,
      "flat": "F-205",
      "src": "bay:B1#122/0",
      "at": [
        364.6,
        574.2
      ]
    },
    {
      "id": "s-105",
      "edge": "e-27",
      "t": 0.813,
      "side": -1,
      "flat": "F-1302",
      "src": "bay:B1#123/0",
      "at": [
        334.5,
        531.3
      ]
    },
    {
      "id": "s-106",
      "edge": "e-27",
      "t": 0.646,
      "side": -1,
      "flat": "F-1102",
      "src": "bay:B1#124/0",
      "at": [
        287.3,
        527.8
      ]
    },
    {
      "id": "s-107",
      "edge": "e-27",
      "t": 0.506,
      "side": 1,
      "flat": "F-1101",
      "src": "bay:B1#125/0",
      "at": [
        247.7,
        536.9
      ]
    },
    {
      "id": "s-108",
      "edge": "e-27",
      "t": 0.352,
      "side": 1,
      "flat": "F-1102",
      "src": "bay:B1#126/0",
      "at": [
        203.4,
        569.1
      ]
    },
    {
      "id": "s-109",
      "edge": "e-27",
      "t": 0.283,
      "side": -1,
      "flat": "F-304",
      "src": "bay:B1#127/0",
      "at": [
        184.9,
        529.1
      ]
    },
    {
      "id": "s-110",
      "edge": "e-27",
      "t": 0.146,
      "side": 1,
      "flat": "F-304",
      "src": "bay:B1#128/0",
      "at": [
        145.3,
        564.9
      ]
    },
    {
      "id": "s-111",
      "edge": "e-27",
      "t": 0.089,
      "side": -1,
      "flat": "F-101",
      "src": "bay:B1#129/0",
      "at": [
        130.5,
        521.8
      ]
    },
    {
      "id": "s-112",
      "edge": "e-25",
      "t": 0.816,
      "side": 1,
      "flat": "F-G5",
      "src": "bay:B1#130/0",
      "at": [
        53.9,
        486.4
      ]
    },
    {
      "id": "s-113",
      "edge": "e-25",
      "t": 0.9,
      "side": 1,
      "flat": "F-402",
      "src": "bay:B1#131/0",
      "at": [
        56.5,
        499.7
      ]
    },
    {
      "id": "s-114",
      "edge": "e-91",
      "t": 0.391,
      "side": -1,
      "flat": "B-1205",
      "src": "bay:B1#132/0",
      "at": [
        882.8,
        573
      ]
    },
    {
      "id": "s-115",
      "edge": "e-91",
      "t": 0.273,
      "side": -1,
      "flat": "B-505",
      "src": "bay:B1#133/0",
      "at": [
        882.3,
        552
      ]
    },
    {
      "id": "s-116",
      "edge": "e-91",
      "t": 0.128,
      "side": -1,
      "flat": "C-203",
      "src": "bay:B1#134/0",
      "at": [
        880.2,
        526.3
      ]
    },
    {
      "id": "s-117",
      "edge": "e-91",
      "t": 0.21,
      "side": 1,
      "flat": "B-802",
      "src": "bay:B1#136/0",
      "at": [
        823.7,
        541.7
      ]
    },
    {
      "id": "s-118",
      "edge": "e-91",
      "t": 0.147,
      "side": 1,
      "flat": "B-1002",
      "src": "bay:B1#137/0",
      "at": [
        766,
        531.2
      ]
    },
    {
      "id": "s-119",
      "edge": "e-36",
      "t": 0.033,
      "side": -1,
      "flat": "B-1304",
      "src": "bay:B1#138/0",
      "at": [
        698.6,
        538.9
      ]
    },
    {
      "id": "s-120",
      "edge": "e-35",
      "t": 0.589,
      "side": -1,
      "flat": "B-1102",
      "src": "bay:B1#139/0",
      "at": [
        690.1,
        487.4
      ]
    },
    {
      "id": "s-121",
      "edge": "e-29",
      "t": 0.905,
      "side": 1,
      "flat": "B-1303",
      "src": "bay:B1#140/0",
      "at": [
        659.5,
        536.6
      ]
    },
    {
      "id": "s-122",
      "edge": "e-29",
      "t": 0.763,
      "side": 1,
      "flat": "D-106",
      "src": "bay:B1#141/0",
      "at": [
        628.8,
        538.7
      ]
    },
    {
      "id": "s-123",
      "edge": "e-29",
      "t": 0.6,
      "side": -1,
      "flat": "D-806",
      "src": "bay:B1#142/0",
      "at": [
        593.5,
        532
      ]
    },
    {
      "id": "s-124",
      "edge": "e-31",
      "t": 0.76,
      "side": -1,
      "flat": "D-1001",
      "src": "bay:B1#143/0",
      "at": [
        470.7,
        511.7
      ]
    },
    {
      "id": "s-125",
      "edge": "e-31",
      "t": 0.703,
      "side": 1,
      "flat": "D-1101",
      "src": "bay:B1#144/0",
      "at": [
        452,
        505
      ]
    },
    {
      "id": "s-126",
      "edge": "e-23",
      "t": 0.463,
      "side": -1,
      "flat": "F-1101",
      "src": "bay:B1#145/0",
      "at": [
        382.7,
        524.2
      ]
    },
    {
      "id": "s-127",
      "edge": "e-22",
      "t": 0.739,
      "side": -1,
      "flat": "F-904",
      "src": "bay:B1#146/0",
      "at": [
        382.9,
        477.9
      ]
    },
    {
      "id": "s-128",
      "edge": "e-22",
      "t": 0.702,
      "side": 1,
      "flat": "F-402",
      "src": "bay:B1#147/0",
      "at": [
        357.4,
        470.8
      ]
    },
    {
      "id": "s-129",
      "edge": "e-22",
      "t": 0.756,
      "side": 1,
      "flat": "F-105",
      "src": "bay:B1#148/0",
      "at": [
        318,
        481.5
      ]
    },
    {
      "id": "s-130",
      "edge": "e-27",
      "t": 0.303,
      "side": -1,
      "flat": "F-901",
      "src": "bay:B1#149/0",
      "at": [
        192.1,
        481.9
      ]
    },
    {
      "id": "s-131",
      "edge": "e-25",
      "t": 0.844,
      "side": -1,
      "flat": "F-301",
      "src": "bay:B1#150/0",
      "at": [
        88.4,
        490.4
      ]
    },
    {
      "id": "s-132",
      "edge": "e-25",
      "t": 0.638,
      "side": 1,
      "flat": "E-102",
      "src": "bay:B1#151/0",
      "at": [
        81.8,
        458.2
      ]
    },
    {
      "id": "s-133",
      "edge": "e-25",
      "t": 0.593,
      "side": 1,
      "flat": "F-G4",
      "src": "bay:B1#152/0",
      "at": [
        51.9,
        451.5
      ]
    },
    {
      "id": "s-134",
      "edge": "e-25",
      "t": 0.684,
      "side": 1,
      "flat": "F-404",
      "src": "bay:B1#153/0",
      "at": [
        52.9,
        465.8
      ]
    },
    {
      "id": "s-135",
      "edge": "e-90",
      "t": 0.609,
      "side": -1,
      "flat": "C-1403",
      "src": "bay:B1#155/0",
      "at": [
        870.5,
        439.5
      ]
    },
    {
      "id": "s-136",
      "edge": "e-90",
      "t": 0.791,
      "side": -1,
      "flat": "C-301",
      "src": "bay:B1#156/0",
      "at": [
        874.1,
        469.3
      ]
    },
    {
      "id": "s-137",
      "edge": "e-90",
      "t": 0.621,
      "side": 1,
      "flat": "B-1205",
      "src": "bay:B1#157/0",
      "at": [
        839.8,
        441.8
      ]
    },
    {
      "id": "s-138",
      "edge": "e-35",
      "t": 0.477,
      "side": -1,
      "flat": "C-1304",
      "src": "bay:B1#158/0",
      "at": [
        747.7,
        473.7
      ]
    },
    {
      "id": "s-139",
      "edge": "e-35",
      "t": 0.369,
      "side": -1,
      "flat": "B-1404",
      "src": "bay:B1#159/0",
      "at": [
        679.5,
        461.6
      ]
    },
    {
      "id": "s-140",
      "edge": "e-35",
      "t": 0.079,
      "side": 1,
      "flat": "C-202",
      "src": "bay:B1#160/0",
      "at": [
        674.8,
        427.4
      ]
    },
    {
      "id": "s-141",
      "edge": "e-33",
      "t": 0.735,
      "side": 1,
      "flat": "C-702",
      "src": "bay:B1#161/0",
      "at": [
        622.2,
        428.6
      ]
    },
    {
      "id": "s-142",
      "edge": "e-33",
      "t": 0.446,
      "side": 1,
      "flat": "D-1102",
      "src": "bay:B1#162/0",
      "at": [
        560,
        421.9
      ]
    },
    {
      "id": "s-143",
      "edge": "e-33",
      "t": 0.285,
      "side": 1,
      "flat": "D-404",
      "src": "bay:B1#163/0",
      "at": [
        525.3,
        425.9
      ]
    },
    {
      "id": "s-144",
      "edge": "e-31",
      "t": 0.269,
      "side": -1,
      "flat": "D-301",
      "src": "bay:B1#164/0",
      "at": [
        475.3,
        453.8
      ]
    },
    {
      "id": "s-145",
      "edge": "e-31",
      "t": 0.078,
      "side": 1,
      "flat": "D-503",
      "src": "bay:B1#165/0",
      "at": [
        459.2,
        431.2
      ]
    },
    {
      "id": "s-146",
      "edge": "e-31",
      "t": 0.303,
      "side": 1,
      "flat": "D-1204",
      "src": "bay:B1#166/0",
      "at": [
        449.9,
        457.8
      ]
    },
    {
      "id": "s-147",
      "edge": "e-22",
      "t": 0.541,
      "side": -1,
      "flat": "F-702",
      "src": "bay:B1#167/0",
      "at": [
        383.5,
        439.8
      ]
    },
    {
      "id": "s-148",
      "edge": "e-22",
      "t": 0.536,
      "side": 1,
      "flat": "F-502",
      "src": "bay:B1#168/0",
      "at": [
        316.2,
        439.2
      ]
    },
    {
      "id": "s-149",
      "edge": "e-22",
      "t": 0.401,
      "side": 1,
      "flat": "F-1301",
      "src": "bay:B1#169/0",
      "at": [
        317,
        413.3
      ]
    },
    {
      "id": "s-150",
      "edge": "e-22",
      "t": 0.667,
      "side": 1,
      "flat": "F-302",
      "src": "bay:B1#170/0",
      "at": [
        310.8,
        464.4
      ]
    },
    {
      "id": "s-151",
      "edge": "e-25",
      "t": 0.496,
      "side": -1,
      "flat": "F-405",
      "src": "bay:B1#172/0",
      "at": [
        84,
        435.8
      ]
    },
    {
      "id": "s-152",
      "edge": "e-25",
      "t": 0.337,
      "side": -1,
      "flat": "F-601",
      "src": "bay:B1#173/0",
      "at": [
        85.7,
        410.8
      ]
    },
    {
      "id": "s-153",
      "edge": "e-25",
      "t": 0.386,
      "side": 1,
      "flat": "F-1402",
      "src": "bay:B1#174/0",
      "at": [
        41.1,
        419.1
      ]
    },
    {
      "id": "s-154",
      "edge": "e-25",
      "t": 0.485,
      "side": 1,
      "flat": "F-G2",
      "src": "bay:B1#175/0",
      "at": [
        49.8,
        434.5
      ]
    },
    {
      "id": "s-155",
      "edge": "e-90",
      "t": 0.346,
      "side": -1,
      "flat": "C-405",
      "src": "bay:B1#176/0",
      "at": [
        871.5,
        396.4
      ]
    },
    {
      "id": "s-156",
      "edge": "e-34",
      "t": 0.443,
      "side": 1,
      "flat": "C-402",
      "src": "bay:B1#178/0",
      "at": [
        675.2,
        372.9
      ]
    },
    {
      "id": "s-157",
      "edge": "e-33",
      "t": 0.889,
      "side": 1,
      "flat": "C-201",
      "src": "bay:B1#179/0",
      "at": [
        655.2,
        422.3
      ]
    },
    {
      "id": "s-158",
      "edge": "e-33",
      "t": 0.767,
      "side": -1,
      "flat": "C-1303",
      "src": "bay:B1#180/0",
      "at": [
        628.7,
        412.1
      ]
    },
    {
      "id": "s-159",
      "edge": "e-33",
      "t": 0.612,
      "side": 1,
      "flat": "D-303",
      "src": "bay:B1#181/0",
      "at": [
        595.7,
        420.3
      ]
    },
    {
      "id": "s-160",
      "edge": "e-33",
      "t": 0.478,
      "side": -1,
      "flat": "D-406",
      "src": "bay:B1#182/0",
      "at": [
        566.7,
        413.4
      ]
    },
    {
      "id": "s-161",
      "edge": "e-33",
      "t": 0.126,
      "side": -1,
      "flat": "D-401",
      "src": "bay:B1#183/0",
      "at": [
        490.9,
        415.4
      ]
    },
    {
      "id": "s-162",
      "edge": "e-30",
      "t": 0.681,
      "side": -1,
      "flat": "D-304",
      "src": "bay:B1#184/0",
      "at": [
        473.7,
        392.4
      ]
    },
    {
      "id": "s-163",
      "edge": "e-30",
      "t": 0.576,
      "side": -1,
      "flat": "D-304",
      "src": "bay:B1#185/0",
      "at": [
        464,
        384.5
      ]
    },
    {
      "id": "s-164",
      "edge": "e-30",
      "t": 0.725,
      "side": 1,
      "flat": "E-405",
      "src": "bay:B1#186/0",
      "at": [
        449,
        399.6
      ]
    },
    {
      "id": "s-165",
      "edge": "e-22",
      "t": 0.156,
      "side": -1,
      "flat": "E-1202",
      "src": "bay:B1#187/0",
      "at": [
        384,
        365.9
      ]
    },
    {
      "id": "s-166",
      "edge": "e-22",
      "t": 0.339,
      "side": -1,
      "flat": "E-1301",
      "src": "bay:B1#188/0",
      "at": [
        381.1,
        401.1
      ]
    },
    {
      "id": "s-168",
      "edge": "e-25",
      "t": 0.153,
      "side": -1,
      "flat": "F-G1",
      "src": "bay:B1#190/0",
      "at": [
        95.3,
        381.9
      ]
    },
    {
      "id": "s-169",
      "edge": "e-25",
      "t": 0.103,
      "side": 1,
      "flat": "F-1402",
      "src": "bay:B1#191/0",
      "at": [
        63.7,
        374.3
      ]
    },
    {
      "id": "s-170",
      "edge": "e-90",
      "t": 0.261,
      "side": -1,
      "flat": "C-205",
      "src": "bay:B1#192/0",
      "at": [
        869.9,
        382.5
      ]
    },
    {
      "id": "s-171",
      "edge": "e-90",
      "t": 0.124,
      "side": -1,
      "flat": "C-504",
      "src": "bay:B1#193/0",
      "at": [
        874.1,
        359.9
      ]
    },
    {
      "id": "s-172",
      "edge": "e-19",
      "t": 0.806,
      "side": 1,
      "flat": "C-1302",
      "src": "bay:B1#194/0",
      "at": [
        813.1,
        368
      ]
    },
    {
      "id": "s-173",
      "edge": "e-19",
      "t": 0.537,
      "side": -1,
      "flat": "C-1201",
      "src": "bay:B1#195/0",
      "at": [
        768.8,
        335.8
      ]
    },
    {
      "id": "s-174",
      "edge": "e-18",
      "t": 0.773,
      "side": -1,
      "flat": "D-901",
      "src": "bay:B1#196/0",
      "at": [
        627.6,
        329.1
      ]
    },
    {
      "id": "s-175",
      "edge": "e-18",
      "t": 0.648,
      "side": -1,
      "flat": "D-1302",
      "src": "bay:B1#197/0",
      "at": [
        599.2,
        327.6
      ]
    },
    {
      "id": "s-176",
      "edge": "e-18",
      "t": 0.476,
      "side": 1,
      "flat": "D-1402",
      "src": "bay:B1#198/0",
      "at": [
        559.9,
        340.1
      ]
    },
    {
      "id": "s-177",
      "edge": "e-18",
      "t": 0.342,
      "side": -1,
      "flat": "D-505",
      "src": "bay:B1#199/0",
      "at": [
        529.7,
        329.2
      ]
    },
    {
      "id": "s-178",
      "edge": "e-18",
      "t": 0.187,
      "side": 1,
      "flat": "D-1103",
      "src": "bay:B1#201/0",
      "at": [
        494.3,
        340.1
      ]
    },
    {
      "id": "s-179",
      "edge": "e-30",
      "t": 0.234,
      "side": 1,
      "flat": "D-801",
      "src": "bay:B1#202/0",
      "at": [
        454.3,
        355.5
      ]
    },
    {
      "id": "s-180",
      "edge": "e-12",
      "t": 0.74,
      "side": 1,
      "flat": "D-801",
      "src": "bay:B1#203/0",
      "at": [
        445.5,
        317.1
      ]
    },
    {
      "id": "s-181",
      "edge": "e-17",
      "t": 0.617,
      "side": 1,
      "flat": "E-805",
      "src": "bay:B1#204/0",
      "at": [
        419.4,
        335.6
      ]
    },
    {
      "id": "s-182",
      "edge": "e-17",
      "t": 0.439,
      "side": -1,
      "flat": "E-1202",
      "src": "bay:B1#205/0",
      "at": [
        404.2,
        330.9
      ]
    },
    {
      "id": "s-183",
      "edge": "e-17",
      "t": 0.287,
      "side": -1,
      "flat": "E-802",
      "src": "bay:B1#206/0",
      "at": [
        391.4,
        332.1
      ]
    },
    {
      "id": "s-184",
      "edge": "e-22",
      "t": 0.078,
      "side": 1,
      "flat": "E-1001",
      "src": "bay:B1#207/0",
      "at": [
        359.2,
        351
      ]
    },
    {
      "id": "s-185",
      "edge": "e-88",
      "t": 0.796,
      "side": -1,
      "flat": "E-304",
      "src": "bay:B1#208/0",
      "at": [
        338.1,
        328.1
      ]
    },
    {
      "id": "s-186",
      "edge": "e-88",
      "t": 0.609,
      "side": 1,
      "flat": "F-503",
      "src": "bay:B1#209/0",
      "at": [
        311.9,
        340.1
      ]
    },
    {
      "id": "s-187",
      "edge": "e-88",
      "t": 0.505,
      "side": -1,
      "flat": "F-1103",
      "src": "bay:B1#210/0",
      "at": [
        297.1,
        337
      ]
    },
    {
      "id": "s-188",
      "edge": "e-88",
      "t": 0.224,
      "side": -1,
      "flat": "F-504",
      "src": "bay:B1#211/0",
      "at": [
        257.4,
        331.1
      ]
    },
    {
      "id": "s-189",
      "edge": "e-14",
      "t": 0.395,
      "side": 1,
      "flat": "E-901",
      "src": "bay:B1#212/0",
      "at": [
        136.9,
        292.6
      ]
    },
    {
      "id": "s-190",
      "edge": "e-87",
      "t": 0.082,
      "side": 1,
      "flat": "F-1304",
      "src": "bay:B1#213/0",
      "at": [
        116.8,
        341.5
      ]
    },
    {
      "id": "s-191",
      "edge": "e-24",
      "t": 0.761,
      "side": 1,
      "flat": "F-102",
      "src": "bay:B1#214/0",
      "at": [
        78.7,
        340.9
      ]
    },
    {
      "id": "s-192",
      "edge": "e-85",
      "t": 0.982,
      "side": -1,
      "flat": "C-605",
      "src": "bay:B1#216/0",
      "at": [
        905.9,
        334.8
      ]
    },
    {
      "id": "s-193",
      "edge": "e-85",
      "t": 0.811,
      "side": -1,
      "flat": "C-801",
      "src": "bay:B1#217/0",
      "at": [
        853.5,
        308.1
      ]
    },
    {
      "id": "s-194",
      "edge": "e-9",
      "t": 0.521,
      "side": -1,
      "flat": "C-803",
      "src": "bay:B1#219/0",
      "at": [
        687.3,
        300.7
      ]
    },
    {
      "id": "s-195",
      "edge": "e-9",
      "t": 0.203,
      "side": -1,
      "flat": "C-602",
      "src": "bay:B1#220/0",
      "at": [
        678.8,
        277.2
      ]
    },
    {
      "id": "s-196",
      "edge": "e-9",
      "t": 0.156,
      "side": 1,
      "flat": "D-1302",
      "src": "bay:B1#221/0",
      "at": [
        644,
        275
      ]
    },
    {
      "id": "s-197",
      "edge": "e-8",
      "t": 0.335,
      "side": 1,
      "flat": "D-204",
      "src": "bay:B1#222/0",
      "at": [
        599.9,
        264
      ]
    },
    {
      "id": "s-198",
      "edge": "e-12",
      "t": 0.171,
      "side": 1,
      "flat": "D-902",
      "src": "bay:B1#223/0",
      "at": [
        436.6,
        276.9
      ]
    },
    {
      "id": "s-199",
      "edge": "e-15",
      "t": 0.852,
      "side": -1,
      "flat": "E-1002",
      "src": "bay:B1#224/0",
      "at": [
        396.6,
        252.4
      ]
    },
    {
      "id": "s-200",
      "edge": "e-15",
      "t": 0.701,
      "side": -1,
      "flat": "E-302",
      "src": "bay:B1#225/0",
      "at": [
        354.3,
        249.1
      ]
    },
    {
      "id": "s-201",
      "edge": "e-15",
      "t": 0.541,
      "side": -1,
      "flat": "E-1004",
      "src": "bay:B1#226/0",
      "at": [
        309.5,
        259.6
      ]
    },
    {
      "id": "s-202",
      "edge": "e-15",
      "t": 0.406,
      "side": -1,
      "flat": "E-404",
      "src": "bay:B1#227/0",
      "at": [
        271.7,
        258.9
      ]
    },
    {
      "id": "s-203",
      "edge": "e-15",
      "t": 0.221,
      "side": -1,
      "flat": "E-704",
      "src": "bay:B1#228/0",
      "at": [
        219.9,
        256.8
      ]
    },
    {
      "id": "s-204",
      "edge": "e-14",
      "t": 0.178,
      "side": 1,
      "flat": "E-901",
      "src": "bay:B1#229/0",
      "at": [
        118.2,
        256.2
      ]
    },
    {
      "id": "s-205",
      "edge": "e-14",
      "t": 0.815,
      "side": 1,
      "flat": "E-1102",
      "src": "bay:B1#230/0",
      "at": [
        92,
        310.6
      ]
    },
    {
      "id": "s-206",
      "edge": "e-14",
      "t": 0.467,
      "side": 1,
      "flat": "E-604",
      "src": "bay:B1#230/1",
      "at": [
        115.7,
        287
      ]
    },
    {
      "id": "s-207",
      "edge": "e-85",
      "t": 0.815,
      "side": -1,
      "flat": "C-1001",
      "src": "bay:B1#231/0",
      "at": [
        872,
        308.1
      ]
    },
    {
      "id": "s-208",
      "edge": "e-85",
      "t": 0.532,
      "side": -1,
      "flat": "C-1104",
      "src": "bay:B1#232/0",
      "at": [
        867.4,
        260.8
      ]
    },
    {
      "id": "s-209",
      "edge": "e-85",
      "t": 0.401,
      "side": -1,
      "flat": "C-705",
      "src": "bay:B1#233/0",
      "at": [
        868.9,
        238.8
      ]
    },
    {
      "id": "s-210",
      "edge": "e-8",
      "t": 0.535,
      "side": -1,
      "flat": "C-G4",
      "src": "bay:B1#234/0",
      "at": [
        675.7,
        238.2
      ]
    },
    {
      "id": "s-211",
      "edge": "e-8",
      "t": 0,
      "side": 1,
      "flat": "D-501",
      "src": "bay:B1#235/0",
      "at": [
        603.3,
        240.7
      ]
    },
    {
      "id": "s-212",
      "edge": "e-82",
      "t": 0.847,
      "side": 1,
      "flat": "D-1104",
      "src": "bay:B1#236/0",
      "at": [
        595,
        217.1
      ]
    },
    {
      "id": "s-213",
      "edge": "e-11",
      "t": 0.719,
      "side": 1,
      "flat": "D-201",
      "src": "bay:B1#237/0",
      "at": [
        439.2,
        216.3
      ]
    },
    {
      "id": "s-214",
      "edge": "e-11",
      "t": 0.892,
      "side": 1,
      "flat": "D-1003",
      "src": "bay:B1#238/0",
      "at": [
        437,
        245.7
      ]
    },
    {
      "id": "s-215",
      "edge": "e-15",
      "t": 0.675,
      "side": -1,
      "flat": "E-202",
      "src": "bay:B1#239/0",
      "at": [
        347.4,
        209.2
      ]
    },
    {
      "id": "s-216",
      "edge": "e-13",
      "t": 0.453,
      "side": 1,
      "flat": "E-204",
      "src": "bay:B1#240/0",
      "at": [
        152.4,
        214.3
      ]
    },
    {
      "id": "s-217",
      "edge": "e-13",
      "t": 0.311,
      "side": 1,
      "flat": "E-1104",
      "src": "bay:B1#241/0",
      "at": [
        127.5,
        201.3
      ]
    },
    {
      "id": "s-218",
      "edge": "e-85",
      "t": 0.656,
      "side": -1,
      "flat": "C-1202",
      "src": "bay:B1#242/0",
      "at": [
        873,
        281.4
      ]
    },
    {
      "id": "s-219",
      "edge": "e-85",
      "t": 0.391,
      "side": -1,
      "flat": "C-802",
      "src": "bay:B1#243/0",
      "at": [
        908.5,
        235.7
      ]
    },
    {
      "id": "s-220",
      "edge": "e-81",
      "t": 0.898,
      "side": 1,
      "flat": "D-1005",
      "src": "bay:B1#244/0",
      "at": [
        655.1,
        189.4
      ]
    },
    {
      "id": "s-221",
      "edge": "e-81",
      "t": 0.732,
      "side": 1,
      "flat": "D-1304",
      "src": "bay:B1#245/0",
      "at": [
        615,
        171.1
      ]
    },
    {
      "id": "s-222",
      "edge": "e-81",
      "t": 0.966,
      "side": 1,
      "flat": "D-702",
      "src": "bay:B1#246/0",
      "at": [
        551.8,
        197.1
      ]
    },
    {
      "id": "s-223",
      "edge": "e-11",
      "t": 0.492,
      "side": 1,
      "flat": "D-703",
      "src": "bay:B1#247/0",
      "at": [
        437.7,
        177.8
      ]
    },
    {
      "id": "s-224",
      "edge": "e-11",
      "t": 0.474,
      "side": 1,
      "flat": "E-202",
      "src": "bay:B1#248/0",
      "at": [
        373.1,
        170.5
      ]
    },
    {
      "id": "s-225",
      "edge": "e-13",
      "t": 0.153,
      "side": -1,
      "flat": "E-302",
      "src": "bay:B1#249/0",
      "at": [
        223.1,
        189.8
      ]
    },
    {
      "id": "s-226",
      "edge": "e-13",
      "t": 0.142,
      "side": -1,
      "flat": "E-403",
      "src": "bay:B1#250/0",
      "at": [
        162.3,
        187.4
      ]
    },
    {
      "id": "s-227",
      "edge": "e-1",
      "t": 0.181,
      "side": -1,
      "flat": "E-G2",
      "src": "bay:B1#251/0",
      "at": [
        159.4,
        162.2
      ]
    },
    {
      "id": "s-228",
      "edge": "e-1",
      "t": 0.187,
      "side": -1,
      "flat": "E-504",
      "src": "bay:B1#252/0",
      "at": [
        131.6,
        161.7
      ]
    },
    {
      "id": "s-229",
      "edge": "e-85",
      "t": 0.275,
      "side": -1,
      "flat": "C-1002",
      "src": "bay:B1#253/0",
      "at": [
        871.5,
        217.7
      ]
    },
    {
      "id": "s-230",
      "edge": "e-84",
      "t": 0.771,
      "side": 1,
      "flat": "C-801",
      "src": "bay:B1#254/0",
      "at": [
        809.9,
        149.4
      ]
    },
    {
      "id": "s-231",
      "edge": "e-11",
      "t": 0.234,
      "side": 1,
      "flat": "D-102",
      "src": "bay:B1#256/0",
      "at": [
        436.8,
        133.9
      ]
    },
    {
      "id": "s-232",
      "edge": "e-78",
      "t": 0.596,
      "side": 1,
      "flat": "E-G5",
      "src": "bay:B1#257/0",
      "at": [
        239.8,
        100.7
      ]
    },
    {
      "id": "s-233",
      "edge": "e-78",
      "t": 0.315,
      "side": -1,
      "flat": "E-G4",
      "src": "bay:B1#258/0",
      "at": [
        209.3,
        94.9
      ]
    },
    {
      "id": "s-234",
      "edge": "e-1",
      "t": 0.656,
      "side": -1,
      "flat": "E-1305",
      "src": "bay:B1#259/0",
      "at": [
        138.3,
        128.4
      ]
    },
    {
      "id": "s-235",
      "edge": "e-84",
      "t": 0.477,
      "side": 1,
      "flat": "C-1305",
      "src": "bay:B1#260/0",
      "at": [
        818.6,
        117.6
      ]
    },
    {
      "id": "s-236",
      "edge": "e-81",
      "t": 0.145,
      "side": 1,
      "flat": "D-902",
      "src": "bay:B1#261/0",
      "at": [
        646.1,
        106.1
      ]
    },
    {
      "id": "s-237",
      "edge": "e-4",
      "t": 0.827,
      "side": 1,
      "flat": "D-1002",
      "src": "bay:B1#262/0",
      "at": [
        620.2,
        93.6
      ]
    },
    {
      "id": "s-238",
      "edge": "e-4",
      "t": 0.711,
      "side": 1,
      "flat": "D-1002",
      "src": "bay:B1#263/0",
      "at": [
        596.3,
        97.2
      ]
    },
    {
      "id": "s-239",
      "edge": "e-4",
      "t": 0.586,
      "side": 1,
      "flat": "D-1005",
      "src": "bay:B1#264/0",
      "at": [
        570.4,
        96.6
      ]
    },
    {
      "id": "s-240",
      "edge": "e-4",
      "t": 0.332,
      "side": 1,
      "flat": "D-1106",
      "src": "bay:B1#266/0",
      "at": [
        517.7,
        94.8
      ]
    },
    {
      "id": "s-241",
      "edge": "e-79",
      "t": 0.616,
      "side": 1,
      "flat": "E-G1",
      "src": "bay:B1#268/0",
      "at": [
        385.5,
        97.4
      ]
    },
    {
      "id": "s-242",
      "edge": "e-79",
      "t": 0.436,
      "side": 1,
      "flat": "E-G3",
      "src": "bay:B1#269/0",
      "at": [
        355.7,
        96.4
      ]
    },
    {
      "id": "s-243",
      "edge": "e-79",
      "t": 0.185,
      "side": 1,
      "flat": "E-804",
      "src": "bay:B1#270/0",
      "at": [
        314.4,
        95.8
      ]
    },
    {
      "id": "s-244",
      "edge": "e-1",
      "t": 1,
      "side": -1,
      "flat": "E-903",
      "src": "bay:B1#271/0",
      "at": [
        138.3,
        95
      ]
    },
    {
      "id": "s-245",
      "edge": "e-5",
      "t": 0.658,
      "side": 1,
      "flat": "C-805",
      "src": "bay:B1#272/0",
      "at": [
        774.4,
        95
      ]
    },
    {
      "id": "s-246",
      "edge": "e-5",
      "t": 0.544,
      "side": 1,
      "flat": "C-502",
      "src": "bay:B1#273/0",
      "at": [
        753.9,
        92.9
      ]
    },
    {
      "id": "s-247",
      "edge": "e-5",
      "t": 0.441,
      "side": 1,
      "flat": "D-1401",
      "src": "bay:B1#274/0",
      "at": [
        735.4,
        94.5
      ]
    },
    {
      "id": "s-248",
      "edge": "e-4",
      "t": 0.611,
      "side": -1,
      "flat": "D-402",
      "src": "bay:B1#276/0",
      "at": [
        574.7,
        61.1
      ]
    },
    {
      "id": "s-249",
      "edge": "e-4",
      "t": 0.281,
      "side": -1,
      "flat": "D-904",
      "src": "bay:B1#277/0",
      "at": [
        506.4,
        64.2
      ]
    },
    {
      "id": "s-250",
      "edge": "e-4",
      "t": 0.14,
      "side": -1,
      "flat": "D-701",
      "src": "bay:B1#278/0",
      "at": [
        477.1,
        62.1
      ]
    },
    {
      "id": "s-251",
      "edge": "e-79",
      "t": 0.941,
      "side": -1,
      "flat": "E-803",
      "src": "bay:B1#279/0",
      "at": [
        439.2,
        61.1
      ]
    },
    {
      "id": "s-252",
      "edge": "e-79",
      "t": 0.717,
      "side": -1,
      "flat": "E-503",
      "src": "bay:B1#280/0",
      "at": [
        402.2,
        65.2
      ]
    },
    {
      "id": "s-253",
      "edge": "e-79",
      "t": 0.496,
      "side": -1,
      "flat": "E-402",
      "src": "bay:B1#281/0",
      "at": [
        365.7,
        67.3
      ]
    },
    {
      "id": "s-254",
      "edge": "e-79",
      "t": 0.285,
      "side": -1,
      "flat": "E-505",
      "src": "bay:B1#282/0",
      "at": [
        330.8,
        68.3
      ]
    },
    {
      "id": "s-255",
      "edge": "e-79",
      "t": 0.09,
      "side": -1,
      "flat": "E-902",
      "src": "bay:B1#283/0",
      "at": [
        298.5,
        71.9
      ]
    },
    {
      "id": "s-256",
      "edge": "e-78",
      "t": 0.853,
      "side": -1,
      "flat": "E-1304",
      "src": "bay:B1#284/0",
      "at": [
        267.7,
        68.8
      ]
    },
    {
      "id": "s-257",
      "edge": "e-78",
      "t": 0.526,
      "side": -1,
      "flat": "E-904",
      "src": "bay:B1#285/0",
      "at": [
        232.2,
        69.8
      ]
    },
    {
      "id": "s-258",
      "edge": "e-2",
      "t": 1,
      "side": -1,
      "flat": "E-1103",
      "src": "bay:B1#287/0",
      "at": [
        166,
        72.9
      ]
    },
    {
      "id": "s-259",
      "edge": "e-78",
      "t": 0.271,
      "side": -1,
      "flat": "E-603",
      "src": "bay:B1#287/1",
      "at": [
        204.5,
        76
      ]
    },
    {
      "id": "s-260",
      "edge": "e-5",
      "t": 0.496,
      "side": -1,
      "flat": "C-1205",
      "src": "bay:B1#288/0",
      "at": [
        745.2,
        40
      ]
    },
    {
      "id": "s-261",
      "edge": "e-4",
      "t": 0.788,
      "side": -1,
      "flat": "D-602",
      "src": "bay:B1#289/0",
      "at": [
        611.2,
        56.5
      ]
    },
    {
      "id": "s-262",
      "edge": "e-4",
      "t": 0.429,
      "side": -1,
      "flat": "D-302",
      "src": "bay:B1#290/0",
      "at": [
        537.2,
        64.7
      ]
    },
    {
      "id": "s-263",
      "edge": "e-60",
      "t": 0.874,
      "side": 1,
      "flat": "A-1106",
      "src": "bay:A-B1#4/0",
      "at": [
        297.5,
        513.5
      ]
    },
    {
      "id": "s-264",
      "edge": "e-61",
      "t": 0.046,
      "side": -1,
      "flat": "A-807",
      "src": "bay:A-B1#5/0",
      "at": [
        331.4,
        449.8
      ]
    },
    {
      "id": "s-265",
      "edge": "e-105",
      "t": 0.59,
      "side": 1,
      "flat": "A-602",
      "src": "bay:A-B1#6/0",
      "at": [
        322,
        361.6
      ]
    },
    {
      "id": "s-266",
      "edge": "e-61",
      "t": 0.14,
      "side": 1,
      "flat": "A-704",
      "src": "bay:A-B1#7/0",
      "at": [
        358.2,
        515.1
      ]
    },
    {
      "id": "s-267",
      "edge": "e-105",
      "t": 0.964,
      "side": 1,
      "flat": "A-304",
      "src": "bay:A-B1#8/0",
      "at": [
        389.7,
        378.6
      ]
    },
    {
      "id": "s-268",
      "edge": "e-61",
      "t": 0.321,
      "side": 1,
      "flat": "A-1506",
      "src": "bay:A-B1#9/0",
      "at": [
        411.1,
        514.6
      ]
    },
    {
      "id": "s-269",
      "edge": "e-61",
      "t": 0.422,
      "side": -1,
      "flat": "A-1207",
      "src": "bay:A-B1#10/0",
      "at": [
        441.4,
        434.9
      ]
    },
    {
      "id": "s-270",
      "edge": "e-106",
      "t": 0.152,
      "side": 1,
      "flat": "A-708",
      "src": "bay:A-B1#11/0",
      "at": [
        432.2,
        364
      ]
    },
    {
      "id": "s-271",
      "edge": "e-106",
      "t": 0.373,
      "side": 1,
      "flat": "A-603",
      "src": "bay:A-B1#12/0",
      "at": [
        484.3,
        363.9
      ]
    },
    {
      "id": "s-272",
      "edge": "e-61",
      "t": 0.621,
      "side": 1,
      "flat": "A-701",
      "src": "bay:A-B1#14/0",
      "at": [
        498.9,
        510.1
      ]
    },
    {
      "id": "s-273",
      "edge": "e-61",
      "t": 0.62,
      "side": -1,
      "flat": "A-705",
      "src": "bay:A-B1#15/0",
      "at": [
        499,
        451.1
      ]
    },
    {
      "id": "s-274",
      "edge": "e-61",
      "t": 0.736,
      "side": -1,
      "flat": "A-1405",
      "src": "bay:A-B1#16/0",
      "at": [
        533,
        447
      ]
    },
    {
      "id": "s-275",
      "edge": "e-106",
      "t": 0.681,
      "side": 1,
      "flat": "A-1406",
      "src": "bay:A-B1#17/0",
      "at": [
        556.9,
        362.2
      ]
    },
    {
      "id": "s-276",
      "edge": "e-61",
      "t": 0.829,
      "side": 1,
      "flat": "A-508",
      "src": "bay:A-B1#19/0",
      "at": [
        559.4,
        518.2
      ]
    },
    {
      "id": "s-277",
      "edge": "e-61",
      "t": 0.896,
      "side": 1,
      "flat": "A-805",
      "src": "bay:A-B1#20/0",
      "at": [
        579.7,
        455.1
      ]
    },
    {
      "id": "s-278",
      "edge": "e-68",
      "t": 0.973,
      "side": 1,
      "flat": "A-207",
      "src": "bay:A-B1#21/0",
      "at": [
        628.5,
        676.6
      ]
    },
    {
      "id": "s-279",
      "edge": "e-68",
      "t": 0.607,
      "side": 1,
      "flat": "A-404",
      "src": "bay:A-B1#22/0",
      "at": [
        629.6,
        630.8
      ]
    },
    {
      "id": "s-280",
      "edge": "e-68",
      "t": 0.265,
      "side": 1,
      "flat": "A-803",
      "src": "bay:A-B1#23/0",
      "at": [
        631,
        588.1
      ]
    },
    {
      "id": "s-281",
      "edge": "e-67",
      "t": 0.942,
      "side": 1,
      "flat": "A-804",
      "src": "bay:A-B1#24/0",
      "at": [
        633.2,
        548.4
      ]
    },
    {
      "id": "s-282",
      "edge": "e-67",
      "t": 0.712,
      "side": 1,
      "flat": "A-406",
      "src": "bay:A-B1#25/0",
      "at": [
        634,
        521.9
      ]
    },
    {
      "id": "s-283",
      "edge": "e-67",
      "t": 0.369,
      "side": 1,
      "flat": "A-208",
      "src": "bay:A-B1#26/0",
      "at": [
        628.2,
        482.4
      ]
    },
    {
      "id": "s-284",
      "edge": "e-67",
      "t": 0.253,
      "side": -1,
      "flat": "A-208",
      "src": "bay:A-B1#27/0",
      "at": [
        649.3,
        469.1
      ]
    },
    {
      "id": "s-285",
      "edge": "e-67",
      "t": 0.253,
      "side": -1,
      "flat": "A-201",
      "src": "bay:A-B1#27/1",
      "at": [
        649.3,
        469.1
      ]
    },
    {
      "id": "s-286",
      "edge": "e-66",
      "t": 0.819,
      "side": -1,
      "flat": "A-608",
      "src": "bay:A-B1#28/0",
      "at": [
        648.1,
        431.2
      ]
    },
    {
      "id": "s-287",
      "edge": "e-66",
      "t": 0.431,
      "side": 1,
      "flat": "A-1208",
      "src": "bay:A-B1#29/0",
      "at": [
        627.4,
        411
      ]
    },
    {
      "id": "s-288",
      "edge": "e-66",
      "t": 0.239,
      "side": -1,
      "flat": "A-901",
      "src": "bay:A-B1#30/0",
      "at": [
        651.2,
        402.3
      ]
    },
    {
      "id": "s-289",
      "edge": "e-64",
      "t": 0.939,
      "side": -1,
      "flat": "A-901",
      "src": "bay:A-B1#31/0",
      "at": [
        632.8,
        354.5
      ]
    },
    {
      "id": "s-290",
      "edge": "e-64",
      "t": 0.28,
      "side": -1,
      "flat": "A-405",
      "src": "bay:A-B1#32/0",
      "at": [
        639.6,
        316.6
      ]
    },
    {
      "id": "s-291",
      "edge": "e-63",
      "t": 0.643,
      "side": -1,
      "flat": "A-405",
      "src": "bay:A-B1#33/0",
      "at": [
        690.5,
        285.4
      ]
    },
    {
      "id": "s-292",
      "edge": "e-77",
      "t": 0.095,
      "side": -1,
      "flat": "A-806",
      "src": "bay:A-B1#34/0",
      "at": [
        719.9,
        627.6
      ]
    },
    {
      "id": "s-293",
      "edge": "e-68",
      "t": 0.55,
      "side": -1,
      "flat": "A-1004",
      "src": "bay:A-B1#35/0",
      "at": [
        679.7,
        623.7
      ]
    },
    {
      "id": "s-294",
      "edge": "e-73",
      "t": 0.843,
      "side": 1,
      "flat": "A-1502",
      "src": "bay:A-B1#36/0",
      "at": [
        681.6,
        550
      ]
    },
    {
      "id": "s-295",
      "edge": "e-73",
      "t": 0.67,
      "side": 1,
      "flat": "A-1003",
      "src": "bay:A-B1#37/0",
      "at": [
        727.7,
        548.5
      ]
    },
    {
      "id": "s-296",
      "edge": "e-69",
      "t": 0.292,
      "side": 1,
      "flat": "A-202",
      "src": "bay:A-B1#39/0",
      "at": [
        728.2,
        391.8
      ]
    },
    {
      "id": "s-297",
      "edge": "e-63",
      "t": 0.443,
      "side": -1,
      "flat": "A-1106",
      "src": "bay:A-B1#40/0",
      "at": [
        713.3,
        265.8
      ]
    },
    {
      "id": "s-298",
      "edge": "e-63",
      "t": 0.285,
      "side": -1,
      "flat": "A-1208",
      "src": "bay:A-B1#41/0",
      "at": [
        729.6,
        247.8
      ]
    },
    {
      "id": "s-299",
      "edge": "e-77",
      "t": 0.348,
      "side": -1,
      "flat": "A-903",
      "src": "bay:A-B1#42/0",
      "at": [
        774.4,
        638.4
      ]
    },
    {
      "id": "s-300",
      "edge": "e-73",
      "t": 0.409,
      "side": 1,
      "flat": "A-G1",
      "src": "bay:A-B1#43/0",
      "at": [
        796.8,
        551.4
      ]
    },
    {
      "id": "s-301",
      "edge": "e-69",
      "t": 0.51,
      "side": 1,
      "flat": "A-1301",
      "src": "bay:A-B1#44/0",
      "at": [
        792.5,
        391
      ]
    },
    {
      "id": "s-302",
      "edge": "e-74",
      "t": 0.862,
      "side": 1,
      "flat": "A-1307",
      "src": "bay:A-B1#45/0",
      "at": [
        820.1,
        224.6
      ]
    },
    {
      "id": "s-303",
      "edge": "e-74",
      "t": 0.631,
      "side": -1,
      "flat": "A-907",
      "src": "bay:A-B1#46/0",
      "at": [
        789.1,
        178.4
      ]
    },
    {
      "id": "s-304",
      "edge": "e-77",
      "t": 0.544,
      "side": -1,
      "flat": "A-1504",
      "src": "bay:A-B1#47/0",
      "at": [
        816.5,
        632.2
      ]
    },
    {
      "id": "s-305",
      "edge": "e-69",
      "t": 0.607,
      "side": -1,
      "flat": "A-1001",
      "src": "bay:A-B1#48/0",
      "at": [
        821,
        382.7
      ]
    },
    {
      "id": "s-306",
      "edge": "e-69",
      "t": 0.701,
      "side": -1,
      "flat": "A-902",
      "src": "bay:A-B1#49/0",
      "at": [
        848.9,
        383
      ]
    },
    {
      "id": "s-307",
      "edge": "e-75",
      "t": 0.385,
      "side": 1,
      "flat": "A-1507",
      "src": "bay:A-B1#50/0",
      "at": [
        871.1,
        218.8
      ]
    },
    {
      "id": "s-308",
      "edge": "e-77",
      "t": 0.711,
      "side": -1,
      "flat": "A-801",
      "src": "bay:A-B1#51/0",
      "at": [
        852.4,
        636.2
      ]
    },
    {
      "id": "s-309",
      "edge": "e-73",
      "t": 0.172,
      "side": 1,
      "flat": "A-607",
      "src": "bay:A-B1#52/0",
      "at": [
        859.6,
        553.5
      ]
    },
    {
      "id": "s-310",
      "edge": "e-72",
      "t": 0.84,
      "side": 1,
      "flat": "A-1501",
      "src": "bay:A-B1#53/0",
      "at": [
        908.5,
        551.7
      ]
    },
    {
      "id": "s-311",
      "edge": "e-69",
      "t": 0.819,
      "side": 1,
      "flat": "A-904",
      "src": "bay:A-B1#54/0",
      "at": [
        883.6,
        386.4
      ]
    },
    {
      "id": "s-312",
      "edge": "e-75",
      "t": 0.784,
      "side": 1,
      "flat": "A-1504",
      "src": "bay:A-B1#55/0",
      "at": [
        919.4,
        213.4
      ]
    },
    {
      "id": "s-313",
      "edge": "e-77",
      "t": 0.961,
      "side": -1,
      "flat": "A-1304",
      "src": "bay:A-B1#56/0",
      "at": [
        906.2,
        635
      ]
    },
    {
      "id": "s-314",
      "edge": "e-71",
      "t": 0.741,
      "side": -1,
      "flat": "A-103",
      "src": "bay:A-B1#57/0",
      "at": [
        954.3,
        502.4
      ]
    },
    {
      "id": "s-315",
      "edge": "e-71",
      "t": 0.538,
      "side": -1,
      "flat": "A-305",
      "src": "bay:A-B1#58/0",
      "at": [
        951.5,
        469.4
      ]
    },
    {
      "id": "s-316",
      "edge": "e-71",
      "t": 0.296,
      "side": -1,
      "flat": "A-1404",
      "src": "bay:A-B1#59/0",
      "at": [
        942.7,
        430.1
      ]
    },
    {
      "id": "s-317",
      "edge": "e-70",
      "t": 0.248,
      "side": 1,
      "flat": "A-1508",
      "src": "bay:A-B1#60/0",
      "at": [
        951.6,
        373.4
      ]
    },
    {
      "id": "s-318",
      "edge": "e-70",
      "t": 1,
      "side": 1,
      "flat": "A-1007",
      "src": "bay:A-B1#61/0",
      "at": [
        958.8,
        313.7
      ]
    },
    {
      "id": "s-319",
      "edge": "e-70",
      "t": 1,
      "side": 1,
      "flat": "A-1007",
      "src": "bay:A-B1#62/0",
      "at": [
        955.6,
        273.3
      ]
    }
  ]
};
