/* GENERATED by the publish backend. Do not hand-edit - the next publish overwrites it. */
var SCANPOINTS = (function () {
  var LIST = [
    { id: "MG", node: "gate", level: "G", audience: "car",
      label: "Main Gate",
      mount: "Guard cabin wall, driver's side.", rev: 1 },

    { id: "RB", node: "main-ramp-foot", level: "P2", audience: "car",
      label: "Foot of the entry ramp",
      mount: "Ramp wall at the bottom.", rev: 1 },

    { id: "VP", node: "visitor", level: "P2", audience: "car",
      label: "Visitor Parking",
      mount: "First pillar of the visitor bays.", rev: 1 },

    { id: "LA", node: "lift-a", level: "P2", audience: "foot",
      label: "Block A Lift",
      mount: "Beside the lift call button.", rev: 1 },

    { id: "LD", node: "lift-d", level: "P2", audience: "foot",
      label: "Block D Lift",
      mount: "Beside the lift call button.", rev: 1 }
  ];

  var RETIRED = [];

  var BY_ID = {};
  LIST.forEach(function (s) { BY_ID[s.id.toUpperCase()] = s; });

  return {
    all: LIST,
    retired: RETIRED,
    byId: function (id) { return BY_ID[String(id || '').toUpperCase()] || null; },
    byNode: function (n) {
      for (var i = 0; i < LIST.length; i++) if (LIST[i].node === n) return LIST[i];
      return null;
    },
    url: function (base, id) { return base.replace(/[/]+$/, '') + '/?s=' + id; }
  };
})();

if (typeof module !== 'undefined' && module.exports) module.exports = SCANPOINTS;
